create:
  is_secure:   on
  credentials: [[ surveyor, manager, administrator]]

edit:
  is_secure:   on
  credentials: [[ surveyor, manager, administrator]]

listall:
  is_secure:   on
  credentials: [[ manager, administrator]]



  