<?php
// auto-generated by sfPropelCrud
// date: 2009/09/03 02:13:18
?>
<?php use_helper('Object') ?>

<?php echo form_tag('department/update') ?>

<?php echo object_input_hidden_tag($department, 'getId') ?>
<div id="LayoutC" class="Layout">
<div id="Center">
<div class="dparts searchResultList">
<div class="parts">
<div class="partsHeading"><h3>All Departments</h3></div>
<div class="block">
<div class="ditem"><div class="item">
<table>
<tbody>
<tr>
  <th>Manager:</th>
  <td><?php echo select_tag('manager_id', objects_for_select($user,'getId','getNickname',$department->getManagerId())) ?></td>
</tr>
<tr>
  <th>Title:</th>
  <td><?php echo object_input_tag($department, 'getTitle', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Description:</th>
  <td><?php echo object_textarea_tag($department, 'getDescription', array (
  'size' => '30x3',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php if ($department->getId()): ?>
<?php echo submit_tag('Save') ?>
  &nbsp;<?php echo link_to('delete', 'department/delete?id='.$department->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'department/show?id='.$department->getId()) ?>
<?php else: ?>
<?php echo submit_tag('Build') ?>
  &nbsp;<?php echo button_to('cancel', 'department/list') ?>
<?php endif; ?>
<?php echo "</form>"?>
</div></div></div>
</div><!-- parts -->
</div><!-- dparts -->
</div><!-- Center -->
</div><!-- Layout -->
