<?php
// auto-generated by sfPropelCrud
// date: 2009/09/03 02:13:18
?>
<div id="LayoutC" class="Layout">
<div id="Center">
<div class="dparts searchResultList">
<div class="parts">
<div class="partsHeading"><h3>All Departments</h3></div>
<div class="block">
<div class="ditem"><div class="item">
<table>
<tbody>
<tr>
<th>Manager: </th>
<td><?php echo $department->getUserRelatedByManagerId()->getNickname() ?></td>
</tr>
<tr>
<th>Title: </th>
<td><?php echo $department->getTitle() ?></td>
</tr>
<tr>
<th>Description: </th>
<td><?php echo $department->getDescription() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $department->getCreatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo button_to('Edit', 'department/edit?id='.$department->getId(),array('style'=>'width:50px')) ?>
&nbsp;<?php echo Button_to('list', 'department/list',array('style'=>'width:50px')) ?>
</div></div></div>
</div><!-- parts -->
</div><!-- dparts -->
</div><!-- Center -->
</div><!-- Layout -->
