# default values
all:
  homepage_max: 10
  active_days:  7
  pager_max:    10
  
  tinymce_options:|
    theme:"advanced",
    plugins:"safari,pagebreak,style,layer,table,filemanager,imagemanager,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount",
    theme_advanced_toolbar_location:"top",
    theme_advanced_toolbar_align:"left",    
    theme_advanced_buttons1:"preview,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,forecolor,backcolor,|,fontselect,fontsizeselect",
    theme_advanced_buttons2:"paste,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,image,code,|,insertdate,inserttime",
    theme_advanced_buttons3:"tablecontrols,|,hr,removeformat,|,sub,sup,|,charmap,emotions,media,|,fullscreen",
#   theme_advanced_buttons4:"fontselect,fontsizeselect",
#   theme_advanced_statusbar_location:"bottom",
    imagemanager_remember_last_path : false,
    theme_advanced_resizing:false
  
    
  sfImageTransformPlugin:
    default_adapter: GD # GD or ImageMagick
    default_image: { mime_type: image/png, filename: Untitled.png }
    font_dir: /usr/share/fonts/truetype/msttcorefonts
    mime_type:
      auto_detect: true
      library: gd_mime_type # Fileinfo (PECL), MIME_Type (PEAR), gd_mime_type (GD)