default:
  http_metas:
    content-type: text/html

  metas:
    title:        Vhome
    robots:       index, follow
    description:  Vhome
    keywords:     XBV,SNS
    language:     en

  stylesheets:    [main]

  javascripts:    []

  has_layout:     on
  layout:         layout
