default:
  http_metas:
    content-type: text/html

  metas:
    title:        XBV_SNS
    robots:       index, follow
    description:  XBV_SNS
    keywords:     XBV, SNS
    language:     en

  stylesheets:    [main]

  javascripts:    []

  has_layout:     on
  layout:         layout
