<?php
// auto-generated by sfPropelCrud
// date: 2009/09/03 02:12:57
?>
<?php use_helper('Object') ?>
<div class="dparts searchResultList">
<div class="parts">
<div class="partsHeading"><h3>Compose a message</h3></div>

<div class="block">
<div class="ditem">
<div class="item">
<?php if($uNum):?>
<?php echo form_tag('message/update') ?>
<?php echo object_input_hidden_tag($message, 'getId') ?>
<table>
<tbody>
<tr>
  <td>To*:<?php echo select_tag('reciever_id',objects_for_select($users, 'getId','getNickname'))?></td>
</tr>
<tr>
  <td>Title*:<?php echo object_input_tag($message, 'getTitle', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <td><?php echo textarea_tag('content', '', 'size=60x20') ?></td>
</tr>
<tr>
  <td>Anonymity:<?php echo object_checkbox_tag($message, 'getAnonymity', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('Send') ?>
<?php echo button_to('Cancel', 'message/list?type=in') ?>
<?php echo "</form>"?>
<?php else:?>
No Reciever in your department.
<?php endif;?>
</div></div></div>
</div><!-- parts -->
</div><!-- dparts -->
