<?php
// auto-generated by sfPropelCrud
// date: 2009/09/03 02:12:57
?>
<?php use_helper('Javascript')?>
<div id="LayoutB" class="Layout">

<div id="Left">
<div class="parts pageNav">
<div class="partsHeading"><h3>XMail</h3></div>
<ul>
<li><?php echo link_to_remote('Compose', array('update'=>'Center','url'=>'message/create')) ?></li>
<li><?php echo link_to ('Inbox', 'message/list?type=in') ?></li>
<li><?php echo link_to ('Sent Mail', 'message/list?type=out') ?></li>
<li><?php echo link_to ('Trash', 'message/list?type=del') ?></li>
</ul>
</div>
</div><!-- Left -->

<div id="Center">
<div class="dparts searchResultList">
<div class="parts">
<div class="partsHeading"><h3><?php echo $category;?></h3></div>

<div class="block">
<div class="ditem">
<div class="item">
<?php if($pager->getNbResults()):?>
<table>
<thead>
<tr>
  <th>Title</th>
<?php if($type=='in'||$type=='del'):?><th>Sender</th><?php endif;?>
<?php if($type=='out'||$type=='del'):?><th>Reciever</th><?php endif;?>
  <th>Anonymity</th>
<?php if($type=='in'||$type=='out'):?><th>Date</th><?php endif;?>
  <th>Action</th>
</tr>
</thead>
<tbody>
<?php foreach ($pager->getResults() as $message): ?>
<tr>
    <td><?php echo link_to_remote($message->getTitle(),array('update'=>'Center','url'=>'message/show?id='.$message->getId())) ?></td>
<?php if($type=='in'||$type=='del'):?><td><?php echo $message->getAnonymity()?'---':$message->getUserRelatedBySenderId()->getNickname() ?></td><?php endif;?>
<?php if($type=='out'||$type=='del'):?><td><?php echo $message->getUserRelatedByRecieverId()->getNickname() ?></td><?php endif;?>
      <td><?php if($message->getAnonymity()) echo "Yes";else echo "No"; ?></td>
<?php if($type=='in'||$type=='out'):?><td><?php echo $message->getCreatedAt() ?></td><?php endif;?>
<td><?php echo button_to('Delete','message/delete?id='.$message->getId().'&type='.$type)?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
<div class="pagerRelative"><p class="number">
<div class="pagerRelative">
<?php include_partial('blog/pager',array('pager' => $pager, 'page_to_link' => 'message/list?type='.$type.'&'))?>
</div>
</div>
<?php else:?>
No message.
<?php endif;?>
</div></div></div>
</div><!-- parts -->
</div><!-- dparts -->
</div><!-- Center -->
</div><!-- Layout -->