<?php
// auto-generated by sfPropelCrud
// date: 2009/09/03 02:12:57
?>
<div class="dparts searchResultList">
<div class="parts">
<div class="partsHeading"><h3><?php echo $message->getTitle() ?></h3></div>

<div class="block">
<div class="ditem">
<div class="item">
<table>
<tbody>
<tr>
<th>Sender: </th>
<td><?php echo $message->getAnonymity()?'Secret':$message->getUserRelatedBySenderId()->getNickname() ?></td>
</tr>
<tr>
<th>Reciever: </th>
<td><?php echo $message->getUserRelatedByRecieverId()->getNickname() ?></td>
</tr>
<tr>
<th>Title: </th>
<td><?php echo $message->getTitle() ?></td>
</tr>
<tr>
<th>Content: </th>
<td><?php echo $message->getContent() ?></td>
</tr>
<tr>
<th>Anonymity: </th>
<td><?php if($message->getAnonymity())echo 'Yes';else echo'No'; ?></td>
</tr>
<tr>
<th>Date: </th>
<td><?php echo $message->getCreatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
</div></div></div>
</div><!-- parts -->
</div><!-- dparts -->
