<?php
// auto-generated by sfPropelCrud
// date: 2009/09/03 02:12:34
?>
<?php use_helper('Object') ?>
<?php echo object_input_hidden_tag($comment, 'getId') ?>
<div id="LayoutC" class="Layout">
<div id="Center">
<div class="dparts searchResultList">
<div class="parts">
<div class="partsHeading"><h3>Comment</h3></div>

<div class="block">
<div class="ditem">
<div class="item">
<?php echo form_tag('comment/update') ?>
<table>
<tbody>
<tr>
  <th>Blog:</th>
  <td><?php echo object_select_tag($comment, 'getBlogId', array (
  'related_class' => 'Blog',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Topic:</th>
  <td><?php echo object_select_tag($comment, 'getTopicId', array (
  'related_class' => 'Topic',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>User*:</th>
  <td><?php echo object_select_tag($comment, 'getUserId', array (
  'related_class' => 'User',
)) ?></td>
</tr>
<tr>
  <th>Content:</th>
  <td><?php $options = array(
	'rich' => 'fck',
	'height' => 500,
	'width'	=> 528,
    'tool'  => 'QQchong',
);
echo textarea_tag('content', '', $options ); 
  ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($comment->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'comment/delete?id='.$comment->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'comment/show?id='.$comment->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'comment/list') ?>
<?php endif; ?>
<?php echo "</form>"?>
</div></div></div>
</div><!-- parts -->
</div><!-- dparts -->
</div><!-- Center -->
</div><!-- Layout -->
