<?php
// auto-generated by sfPropelCrud
// date: 2009/09/03 02:12:34
?>
<?php use_helper('Javascript')?>
<?php if($cNum):?>
<?php foreach($comments as $comment):?>
<table>
<tbody>
<tr>
<td align="left"><?php echo $comment->getUser()->getNickname() ?></td>
<td align="right"><?php echo $comment->getCreatedAt() ?></td>
</tr>
<tr>
<td><?php echo $comment->getContent() ?></td>
</tr>
</tbody>
</table>
<?php endforeach;?>
<?php else:?>
No comment.
<?php endif;?>
