<?php
// auto-generated by sfPropelCrud
// date: 2009/09/03 02:12:34
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $comment->getId() ?></td>
</tr>
<tr>
<th>Blog: </th>
<td><?php echo $comment->getBlogId() ?></td>
</tr>
<tr>
<th>Topic: </th>
<td><?php echo $comment->getTopicId() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $comment->getUserId() ?></td>
</tr>
<tr>
<th>Content: </th>
<td><?php echo $comment->getContent() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $comment->getCreatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'comment/edit?id='.$comment->getId()) ?>
&nbsp;<?php echo link_to('list', 'comment/list') ?>
