all:
  is_secure:   off

listall:
  is_secure:   on
  credentials: [[ manager, administrator]]

approve:
  is_secure:   on
  credentials: [[ manager, administrator]]

delete:
  is_secure:   on
  credentials: [[ manager, administrator]]  