<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:34:38
?>
<div id="sf_admin_container">

<h1>志愿者信息</h1>

<?php use_helper('Object') ?>

<?php echo form_tag('user/update') ?>

<?php echo object_input_hidden_tag($user, 'getUserId') ?>

<div id="sf_admin_content">

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <label for="user_username" class="required">用户名：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getUserName', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="user_nickname" class="required">昵称：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getNickname', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="user_password" class="required">密码：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getPassword', array (
  'size' => 80,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="user_name" class="required">姓名：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getName', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="user_photo" class="required">照片：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getPhoto', array (
  'size' => 80,
  )) ?>
  </div>
</div>  
  
<div class="form-row">
  <label for="user_bbs_id" class="required">BBS 帐号：</label> 
  <div class="content">      
  <?php echo object_input_tag($user, 'getBbsId', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="user_ofs_id" class="required">OFS 帐号：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getOfsId', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="user_duty" class="required">职务：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getDuty', array (
  'size' => 80,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="user_created_at" class="required">创建日期：</label> 
  <div class="content">    
  <?php echo object_input_date_tag($user, 'getCreateAt', array (
  'rich' => true,
  'withtime' => true,
  )) ?>
  </div>
</div> 

<div class="form-row">
  <label for="user_mobile" class="required">移动电话：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getMobile', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="user_tel" class="required">固定电话：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getTel', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="user_role" class="required">权限：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getUsertype', array (
  'size' => 7,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="user_identity" class="required">身份：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getIdentity', array (
  'size' => 7,
  )) ?>
  </div>
</div>  
  
<div class="form-row">
  <label for="user_email" class="required">Email：</label> 
  <div class="content">      
  <?php echo object_input_tag($user, 'getEmail', array (
  'size' => 32,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="user_qq" class="required">QQ：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getQq', array (
  'size' => 32,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="user_msn" class="required">Msn：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getMsn', array (
  'size' => 32,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="user_address" class="required">地址：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getAddress', array (
  'size' => 80,
  )) ?>
  </div>
</div>  

 
  
</fieldset>

<?php echo submit_tag('save') ?>
<?php if ($user->getUserId()): ?>
  &nbsp;<?php echo link_to('delete', 'user/delete?user_id='.$user->getUserId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'user/show?user_id='.$user->getUserId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'user/list') ?>
<?php endif; ?>
</form>
</div>
</div>

