<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:33:53
?>
<div id="sf_admin_container">

<h1>学校信息</h1>

<?php use_helper('Object') ?>

<div id="sf_admin_content">

<table>
  <tbody>
  <tr>
    <td class="name">学校：</td>
    <td class="content"><?php echo $school->getSchoolId() ?></td>
  </tr>  
  <tr>
    <td class="name">资助点：</td>
    <td class="content"><?php echo $school->getSiteId() ?></td>
  </tr>    
  <tr>
    <td class="name">类型：</td>
    <td class="content"><?php echo $school->getType() ?></td>
  </tr>    
  <tr>
    <td class="name">校长：</td>
    <td class="content"><?php echo $school->getMaster() ?></td>
  </tr>
  <tr>
    <td class="name">联系人：</td>
    <td class="content"><?php echo $school->getContact() ?></td>
  </tr>
  <tr>
    <td class="name">电话：</td>
    <td class="content"><?php echo $school->getPhone() ?></td>
  </tr> 
  <tr>
    <td class="name">地址：</td>
    <td class="content"><?php echo $school->getAddress() ?></td>
  </tr>
  <tr>
    <td class="name">邮编：</td>
    <td class="content"><?php echo $school->getPostal() ?></td>
  </tr>
  <tr>
    <td class="name">简介：</td>
    <td class="content"><?php echo $school->getDiscription() ?></td>
  </tr>                 
  </tbody>
</table>
<?php echo link_to('edit', 'school/edit?school_id='.$school->getSchoolId()) ?>
&nbsp;<?php echo link_to('list', 'school/list') ?>
</div>
</div>