<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:33:53
?>
<div id="sf_admin_container">

<h1>学校信息</h1>

<?php use_helper('Object') ?>

<?php echo form_tag('school/update') ?>

<?php echo object_input_hidden_tag($school, 'getSchoolId') ?>

<div id="sf_admin_content">

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <label for="school_site_id" class="required">项目号：</label> 
  <div class="content">   
  <?php echo object_select_tag($school, 'getSiteId', array (
  'related_class' => 'ProjectSite',
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="school_school_name" class="required">学校名：</label> 
  <div class="content">   
  <?php echo object_input_tag($school, 'getSchoolName', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="school_type" class="required">类型：</label> 
  <div class="content">   
  <?php echo object_input_tag($school, 'getType', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="school_master" class="required">校长：</label> 
  <div class="content">   
  <?php echo object_input_tag($school, 'getMaster', array (
  'size' => 20,
  )) ?>
  </div>
</div>
  
<div class="form-row">
  <label for="school_contact" class="required">联系人：</label> 
  <div class="content">   
  <?php echo object_input_tag($school, 'getContact', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="school_phone" class="required">电话：</label> 
  <div class="content">   
  <?php echo object_input_tag($school, 'getPhone', array (
  'size' => 32,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="school_address" class="required">地址：</label> 
  <div class="content">   
  <?php echo object_input_tag($school, 'getAddress', array (
  'size' => 80,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="school_postal" class="required">邮政编码：</label> 
  <div class="content">   
  <?php echo object_input_tag($school, 'getPostal', array (
  'size' => 20,
  )) ?>
  </div>
</div>  
  
<div class="form-row">
  <label for="school_discription" class="required">简介：</label> 
  <div class="content">   
  <?php echo object_input_tag($school, 'getDiscription', array (

  )) ?>
  </div>
</div>  

  
</fieldset>
<?php echo submit_tag('save') ?>
<?php if ($school->getSchoolId()): ?>
  &nbsp;<?php echo link_to('delete', 'school/delete?school_id='.$school->getSchoolId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'school/show?school_id='.$school->getSchoolId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'school/list') ?>
<?php endif; ?>
</form>

</div>
</div>
