<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:33:53
?>
<div id="sf_admin_container">
<h1>所有学校信息</h1>

<?php if(sizeof($pager->getResults()) != 0):?>
<div id="sf_admin_content">
<table cellspacing="0" class="sf_admin_list">

<thead>
<tr>
  <th>学校名</th>
  <th>项目点</th>
  <th>类型</th>
  <th>校长</th>
  <th>联系人</th>
  <th>电话</th>
  <th>操作</th>
</tr>
</thead>
<tbody>
<?php $count_row = 0?>
<?php foreach ($pager->getResults() as $school): ?>

  <?php echo "<tr class='sf_admin_row_".$count_row."' >" ?>
      <td><?php echo $school->getSchoolName() ?></td>  
      <td><?php echo link_to ($school->getProjectSite()->getSiteName(), '@site_show?site_id='.$school->getSiteId()) ?></td>
      <td><?php echo $school->getType() ?></td>
      <td><?php echo $school->getMaster() ?></td>
      <td><?php echo $school->getContact() ?></td>
      <td><?php echo $school->getPhone() ?></td>
      <td>
      <?php
        echo link_to('详情', '@school_show?school_id='.$school->getSchoolId());
        echo "&nbsp;&nbsp;&nbsp;";
        echo link_to('修改', '@school_edit?school_id='.$school->getSchoolId());
      ?>
      </td>
  <?php
    if($count_row)
       $count_row = 0;
    else
       $count_row = 1;
  ?>         
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php include_partial('pager',array('pager' => $pager, 'has_site' =>  0 ))?>

<?php else:?>
无相关记录<br/>
<?php endif;?>

<?php echo link_to ('新建学校', '@school_create') ?>
&nbsp;&nbsp;&nbsp;<a href="javascript:history.go(-1)">返回</a>
</div>
</div>