<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:32:17
?>

<div id="sf_admin_container">
<h1>捐助信息</h1>

<?php if(sizeof($pager->getResults()) != 0):?>
<div id="sf_admin_content">
<table cellspacing="0" class="sf_admin_list">

<thead>
<tr>
  <th>捐助号</th>
  <th>学生姓名</th>
  <th>捐助人姓名</th>
  <th>捐助金额</th>
  <th>开始资助于</th>
  <th>终止资助于</th>
  <th>已批准</th>
  <th>进行中</th>  
  <th>提交于</th>
  <th>操作</th>
</tr>
</thead>
<tbody>
<?php $count_row = 0?>
<?php foreach ($pager->getResults() as $donation): ?>

  <?php echo "<tr class='sf_admin_row_".$count_row."' >" ?>
      <td><?php echo link_to($donation->getDonationId(), 'donation/show?donation_id='.$donation->getDonationId()) ?></td>
      <td><?php echo $donation->getStudent()->getName() ?></td>
      <td><?php echo $donation->getUser()->getName() ?></td>
      <td><?php echo $donation->getAmount() ?></td>      
      <td><?php echo $donation->getStartDate() ?></td>
      <td><?php echo $donation->getEndDate() ?></td>
      <td><?php if ($donation->getApprove()) echo image_tag('admin_db/tick.png'); else echo image_tag('admin_db/x.png'); ?></td>
      <td><?php if ($donation->getIsActive()) echo image_tag('admin_db/tick.png'); else echo image_tag('admin_db/x.png'); ?></td>
      <td><?php echo $donation->getCreatedAt() ?></td>
      <td><?php if (($sf_user->getAttribute('user_id', '')==$donation->getUserId()) || ($sf_user->getAttribute('usertype', '')=='manager')
                    || ($sf_user->getAttribute('usertype', '')=='administrator'))
                {         
                   echo link_to('修改', 'donation/edit?donation_id='.$donation->getDonationId());
                   echo "&nbsp;&nbsp;&nbsp;";
                   echo link_to('删除', 'donation/delete?donation_id='.$donation->getDonationId(), 'post=true&confirm=真的要删除么？');
                }
           ?>
      </td>

  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php include_partial('pager',array('pager' => $pager, 'page_to_link' => 'listpend' ))?>

<?php else:?>
无相关记录<br/>
<?php endif;?>


</div>
</div>
