<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:32:17
?>
<div id="sf_admin_container">

<h1>捐助信息</h1>

<?php use_helper('Object') ?>

<div id="sf_admin_content">

<table>
  <tbody>
  <tr>
    <td class="name">捐助号：</td>
    <td class="content"><?php echo $donation->getDonationId() ?></td>
  </tr>
  <tr>
    <td class="name">学生：</td>
    <td class="content"><?php echo $donation->getStudent()->getName() ?></td>
  </tr>

  <tr>
    <td class="name">志愿者：</td>
    <td class="content"><?php echo $donation->getUser()->getName() ?></td>
  </tr>

  <tr>
    <td class="name">已审批：</td>
    <td class="content"><?php if($donation->getApprove()) echo image_tag('admin_db/tick.png'); else echo image_tag('admin_db/x.png');?></td>
  </tr>  

  <tr>
    <td class="name">有效：</td>
    <td class="content"><?php if($donation->getIsActive()) echo image_tag('admin_db/tick.png'); else echo image_tag('admin_db/x.png');?></td>
  </tr>  
  </tbody>
</table>

<?php echo link_to('修改', 'donation/edit?donation_id='.$donation->getDonationId()) ?>
&nbsp;<?php echo link_to('返回', 'donation/list') ?>

</div>
</div>