<?php
// auto-generated by sfPropelCrud
// date: 2009/09/03 02:12:21
?>
<?php use_helper('Javascript')?>
<div id="LayoutA" class="Layout">
<div id="Left">

<div class="parts memberImageBox">
<p class="photo"><?php echo link_to(image_tag($blog->getUser()->getPhoto()?'users/'.$blog->getUser()->getPhoto():'no_image.gif',array('size'=>'120x120')),'user/show?id='.$blog->getUser()->getId())?></p>
<p class="text"><?php echo $blog->getUser()->getNickname()?></p>
</div>
<div class="parts pageNav">
<div class="partsHeading"><h3>Actions</h3></div>
<ul>
<li id='recommend'><?php echo link_to_remote('recommend the blog',array('update'=>'recommend','url'=>'blog/recommend?id='.$blog->getId()))?></li>
<?php if($user==$blog->getUser()->getId()):?>
<li><?php echo link_to("Post a blog","blog/create")?></li>
<li><?php echo link_to("Edit the blog","blog/edit?id=".$blog->getId())?></li>
<li><?php echo link_to('Delete the blog', 'blog/delete?id='.$blog->getId(), 'post=true&confirm=Are you sure?')?></li>
<?php endif;?>
<li><?php echo link_to("List all blogs","blog/list?userid=".$blog->getUser()->getId())?></li>
</ul>
</div>
</div><!-- Left -->
<script type="text/javascript">
function display(edit,obj)
{
	var usual = "usual" + obj;
	var edit = "edit" + obj;
	document.getElementById(usual).style.display=edit?"none":"block";
	document.getElementById(edit).style.display=edit?"block":"none";
}
</script>
<div id="Center">
<div class="dparts recentList"><div class="parts">
<div class="partsHeading"><h3><?php echo $blog->getTitle() ?></h3></div>
<table>
<tbody>
<tr>
<td><?php echo $blog->getContent() ?></td>
</tr>
</tbody>
</table>
<div class="partsHeading"><h3>Comments</h3></div>
<?php if($pager->getNbResults()):?>
<?php foreach($pager->getResults() as $comment):?>
<table id="comments">
<tbody>
<?php if($user==$comment->getUser()->getId()):?>
<tr>
<td><?php echo $comment->getCreatedAt() ?>:<?php echo $comment->getUser()->getNickname() ?>---<?php echo link_to_function('Edit','display(1,'.$comment->getId().')')?></td>
</tr>
<tr>
<td id="usual<?php echo $comment->getId()?>" style="display:block;"><?php echo $comment->getContent() ?></td>
<td id="edit<?php echo $comment->getId()?>" style="display:none;">
<?php echo form_tag('comment/update') ?>
<?php echo input_hidden_tag('id',$comment->getId())?>
<?php $options = array(
	'rich' => 'fck',
	'height' => 150,
	'width'	=> 720,
    'tool'  => 'Basic',
);
echo textarea_tag('content', $comment->getContent(), $options ); 
  ?>
<?php echo submit_tag('Update') ?>
<?php echo button_to_function('Cancle','display(0,'.$comment->getId().')')?>
<?php echo "</form>"?>
</td>
</tr>
<?php else:?>
<tr>
<td><?php echo $comment->getCreatedAt() ?>:<?php echo $comment->getUser()->getNickname() ?></td>
</tr>
<tr>
<td><?php echo $comment->getContent() ?></td>
</tr>
<?php endif;?>
</tbody>
</table>
<?php endforeach;?>
<div class="pagerRelative"><p class="number">
<div class="pagerRelative">
<?php include_partial('pager',array('pager' => $pager, 'page_to_link' => 'blog/show?id='.$blog->getId().'&' ))?>
</div>
</div>
<?php else:?>
No comment.
<?php endif;?>
<?php echo form_tag('comment/update') ?>
<?php echo input_hidden_tag('blog_id',$blog->getId())?>
<?php $options = array(
	'rich' => 'fck',
	'height' => 150,
	'width'	=> 720,
    'tool'  => 'Basic',
);
echo textarea_tag('content', '', $options ); 
  ?>
<?php echo submit_tag('Publish') ?>
<?php echo "</form>"?>
</div></div>
</div><!-- Center -->
</div><!-- Layout -->
