<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:33:39
?>
<div id="sf_admin_container">

<h1>成绩单</h1>

<?php use_helper('Object') ?>

<?php echo form_tag('reportcard/update') ?>

<?php echo object_input_hidden_tag($report_card, 'getReportId') ?>
<?php echo object_input_hidden_tag($report_card, 'getStudentId') ?>
<?php echo object_input_hidden_tag($report_card, 'getUserId') ?>

<div id="sf_admin_content">

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <label for="report_card_student_id" class="required">学生：</label> 
  <div class="content">   
  <?php echo $student->getName()?>
  </div>
</div>  

<div class="form-row">
  <label for="report_card_student_id" class="required">录入人：</label> 
  <div class="content">   
  <?php echo $user->getName() ?>
  </div>
</div> 

<div class="form-row">
  <label for="report_card_term" class="required">学期：</label> 
  <div class="content">   
  <?php echo object_input_tag($report_card, 'getTerm', array (
  'size' => 15,
  )) ?>
  </div>
</div>
  
<div class="form-row">
  <label for="report_card_yuwen" class="required">语文：</label> 
  <div class="content">   
  <?php echo object_input_tag($report_card, 'getYuwen', array (
  'size' => 7,
  )) ?>
  </div>
</div>

<div class="form-row">
  <label for="report_card_shuxue" class="required">数学：</label> 
  <div class="content">   
  <?php echo object_input_tag($report_card, 'getShuxue', array (
  'size' => 7,
   )) ?>
   </div>
</div>   

<div class="form-row">
  <label for="report_card_yingyu" class="required">英语：</label> 
  <div class="content">      
  <?php echo object_input_tag($report_card, 'getYingyu', array (
  'size' => 7,
  )) ?>
  </div>
</div>  
  
<div class="form-row">
  <label for="report_card_wuli" class="required">物理：</label> 
  <div class="content">     
  <?php echo object_input_tag($report_card, 'getWuli', array (
  'size' => 7,
  )) ?>
  </div>
</div>  
  
<div class="form-row">
  <label for="report_card_huaxue" class="required">化学：</label> 
  <div class="content">     
  <?php echo object_input_tag($report_card, 'getHuaxue', array (
  'size' => 7,
  )) ?>
  </div>
</div>  
  
<div class="form-row">
  <label for="report_card_lishi" class="required">历史：</label> 
  <div class="content">     
  <?php echo object_input_tag($report_card, 'getLishi', array (
  'size' => 7,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="report_card_dili" class="required">地理：</label> 
  <div class="content">   
  <?php echo object_input_tag($report_card, 'getDili', array (
  'size' => 7,
  )) ?>
  </div>
</div>  
  
<div class="form-row">
  <label for="report_card_ziran" class="required">自然：</label> 
  <div class="content">     
  <?php echo object_input_tag($report_card, 'getZiran', array (
  'size' => 7,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="report_card_shengwu" class="required">生物：</label> 
  <div class="content">   
  <?php echo object_input_tag($report_card, 'getShengwu', array (
  'size' => 7,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="report_card_tiyu" class="required">体育：</label> 
  <div class="content">     
  <?php echo object_input_tag($report_card, 'getTiyu', array (
  'size' => 7,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="report_card_zhengzhi" class="required">政治：</label> 
  <div class="content">   
  <?php echo object_input_tag($report_card, 'getZhengzhi', array (
  'size' => 7,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="report_card_zonghe" class="required">综合：</label> 
  <div class="content">   
  <?php echo object_input_tag($report_card, 'getZonghe', array (
  'size' => 7,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="report_card_rank" class="required">排名：</label> 
  <div class="content">   
  <?php echo object_input_tag($report_card, 'getRank', array (
  'size' => 7,
  )) ?>
  </div>
</div>

<div class="form-row">
  <label for="report_card_teacher_remark" class="required">老师评语：</label> 
  <div class="content">     
  <?php echo object_textarea_tag($report_card,'getTeacherRemark', $options = array('size' =>  '70x7')) ?>
  </div>
</div>  

</fieldset>
<?php echo submit_tag('提交') ?>
&nbsp;&nbsp;&nbsp;<a href="javascript:history.go(-1)">返回</a>

</form>
</div>
</div>
