<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:33:39
?>
<div id="sf_admin_container">
<h1>成绩单</h1>

<?php if(sizeof($pager->getResults()) != 0):?>
<div id="sf_admin_content">
<table cellspacing="0" class="sf_admin_list">

<thead>
<tr>
  <th>学生姓名</th>
  <th>录入人</th>
  <th>学期</th>    
  <th>语文</th>
  <th>数学</th>
  <th>英语</th>
  <th>物理</th>
  <th>化学</th>
  <th>历史</th>
  <th>地理</th>
  <th>自然</th>
  <th>生物</th>
  <th>体育</th>
  <th>政治</th>
  <th>综合</th>
  <th>排名</th>
  <th>老师评语</th>

  <th>创建于</th>  
  <th>操作</th>  
</tr>
</thead>
<tbody>
<?php $count_row = 0?>
<?php foreach ($pager->getResults() as $report_card): ?>
  <?php echo "<tr class='sf_admin_row_".$count_row."' >" ?>
      <td><?php echo $report_card->getStudent()->getName() ?></td>
      <td><?php echo $report_card->getUser()->getName() ?></td>      
      <td><?php echo $report_card->getTerm() ?></td>      
      <td><?php echo $report_card->getYuwen() ?></td>
      <td><?php echo $report_card->getShuxue() ?></td>
      <td><?php echo $report_card->getYingyu() ?></td>
      <td><?php echo $report_card->getWuli() ?></td>
      <td><?php echo $report_card->getHuaxue() ?></td>
      <td><?php echo $report_card->getLishi() ?></td>
      <td><?php echo $report_card->getDili() ?></td>
      <td><?php echo $report_card->getZiran() ?></td>
      <td><?php echo $report_card->getShengwu() ?></td>
      <td><?php echo $report_card->getTiyu() ?></td>
      <td><?php echo $report_card->getZhengzhi() ?></td>
      <td><?php echo $report_card->getZonghe() ?></td>
      <td><?php echo $report_card->getRank() ?></td>
      <td><?php echo $report_card->getTeacherRemark() ?></td>
      <td><?php echo $report_card->getCreatedAt() ?></td>  
      <td><?php echo link_to('详情 ', 'reportcard/show?report_id='.$report_card->getReportId())?>
          <?php if (($sf_user->getAttribute('usertype', '')=='surveyor') || ($sf_user->getAttribute('usertype', '')=='manager')
                     || ($sf_user->getAttribute('usertype', '')=='administrator'))
                {      
                   echo link_to('修改 ', '@score_edit?report_id='.$report_card->getReportId());
                }
          ?>
      </td>    
  <?php
    if($count_row)
       $count_row = 0;
    else
       $count_row = 1;
  ?>       
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php include_partial('pager',array('pager' => $pager , 'page_to_link' => '@score_by_student' , 'flag_no_all' => 1 ))?>

<?php else:?>
无相关记录<br/>
<?php endif;?>

<?php if (($sf_user->getAttribute('usertype', '')=='surveyor') || ($sf_user->getAttribute('usertype', '')=='manager')
                     || ($sf_user->getAttribute('usertype', '')=='administrator'))
      {
          echo link_to ('创建成绩单', '@score_create?student_id='.$sf_params->get('student_id'));
      }
 ?>
&nbsp;&nbsp;&nbsp;<a href="javascript:history.go(-1)">返回</a>
</div>
</div>
