<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:33:39
?>
<div id="sf_admin_container">

<h1>成绩单</h1>

<?php use_helper('Object') ?>

<div id="sf_admin_content">

<table>
  <tbody>
  <tr>
    <td class="name">成绩单号：</td>
    <td class="content"><?php echo $report_card->getReportId() ?></td>
  </tr>
  <tr>
    <td class="name">学生：</td>
    <td class="content"><?php echo $report_card->getStudent()->getName() ?></td>
  </tr>
  <tr>
    <td class="name">录入人：</td>
    <td class="content"><?php echo $report_card->getUser()->getName() ?></td>
  </tr>        
  <tr>
    <td class="name">语文：</td>
    <td class="content"><?php echo $report_card->getYuwen() ?></td>
  </tr>
  <tr>
    <td class="name">数学：</td>
    <td class="content"><?php echo $report_card->getShuxue() ?></td>
  </tr>  
  <tr>
    <td class="name">英语：</td>
    <td class="content"><?php echo $report_card->getYingyu() ?></td>
  </tr>  
  <tr>
    <td class="name">物理：</td>
    <td class="content"><?php echo $report_card->getWuli() ?></td>
  </tr>  
  <tr>
    <td class="name">化学：</td>
    <td class="content"><?php echo $report_card->getHuaxue() ?></td>
  </tr>  
  <tr>
    <td class="name">历史：</td>
    <td class="content"><?php echo $report_card->getLishi() ?></td>
  </tr>  
  <tr>
    <td class="name">地理：</td>
    <td class="content"><?php echo $report_card->getDili() ?></td>
  </tr>  
  <tr>
    <td class="name">自然：</td>
    <td class="content"><?php echo $report_card->getZiran() ?></td>
  </tr>  
  <tr>
    <td class="name">生物：</td>
    <td class="content"><?php echo $report_card->getShengwu() ?></td>
  </tr>  
  <tr>
    <td class="name">体育：</td>
    <td class="content"><?php echo $report_card->getTiyu() ?></td>
  </tr>  
  <tr>
    <td class="name">政治：</td>
    <td class="content"><?php echo $report_card->getZhengzhi() ?></td>
  </tr>  
  <tr>
    <td class="name">综合：</td>
    <td class="content"><?php echo $report_card->getZonghe() ?></td>
  </tr>  
  <tr>
    <td class="name">排名：</td>
    <td class="content"><?php echo $report_card->getRank() ?></td>
  </tr>  
  <tr>
    <td class="name">老师评语：</td>
    <td class="content"><?php echo $report_card->getTeacherRemark() ?></td>
  </tr>
  </tbody>
</table>
<?php /*if (($sf_user->getAttribute('usertype', '')=='administrator') || ($sf_user->getAttribute('usertype', '')=='manager')
          ||($sf_user->getAttribute('usertype', '')=='surveyor'))
      {  
      	  echo link_to('修改', 'reportcard/edit?report_id='.$report_card->getReportId()); 
      }*/
 ?>
<?php if ($sf_params->has('after_edit')): ?>
<a href="javascript:history.go(-2)">返回</a>
<?php else:?>
<a href="javascript:history.go(-1)">返回</a>
<?php endif;?>     

</div>
</div>