#donation
donation_approve:
  url:   /donation_approve
  param: { module: donation, action: approve }

donation_create:
  url:   /donation_create/:student_id
  param: { module: donation, action: create }
  
donation_edit:
  url:   /donation_edit/:donation_id
  param: { module: donation, action: edit }
  
donation_my:
  url:   /donation_my
  param: { module: donation, action: listmy }

donation_overdue:
  url:   /donation_overdue
  param: { module: donation, action: listold }  

donation_pending:
  url:   /donation_pending
  param: { module: donation, action: listpend }  

donation_student:
  url:   /donation_student/:student_id/*
  param: { module: donation, action: liststu }
  
donation_show:
  url:   /donation_show/:donation_id/*
  param: { module: donation, action: show }
  
donation_update:
  url:   /donation_update
  param: { module: donation, action: update }        

#investigation
investigation_add:
  url:   /investigation_add
  param: { module: investigation, action: insert }      
investigation_refresh:
  url:   /investigation_refresh
  param: { module: investigation, action: update }      

#login
login:
  url:   /login
  param: { module: login, action: login }      

#project site
site_edit:
  url:   /site_edit/:site_id
  param: { module: projectsite, action: edit }

site_list:
  url:   /site_list/*
  param: { module: projectsite, action: list }
  
site_update:
  url:   /site_update
  param: { module: projectsite, action: update }

site_show:
  url:   /site_show/:site_id/*
  param: { module: projectsite, action: show }


# default rules
homepage:
  url:   /
  param: { module: login, action: login }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
