#donation
donation_approve:
  url:   /donation_approve/*
  param: { module: donation, action: approve }

donation_create:
  url:   /donation_create/:student_id
  param: { module: donation, action: create }
  
donation_edit:
  url:   /donation_edit/:donation_id
  param: { module: donation, action: edit }
  
donation_my:
  url:   /donation_my/*
  param: { module: donation, action: listmy }

donation_overdue:
  url:   /donation_overdue/*
  param: { module: donation, action: listold }  

donation_pending:
  url:   /donation_pending/*
  param: { module: donation, action: listpend }  

donation_student:
  url:   /donation_student/:student_id/*
  param: { module: donation, action: liststu }
  
donation_show:
  url:   /donation_show/:donation_id/*
  param: { module: donation, action: show }
  
donation_update:
  url:   /donation_update
  param: { module: donation, action: update }        

#investigation
investigation_add:
  url:   /investigation_add
  param: { module: investigation, action: insert }      
investigation_refresh:
  url:   /investigation_refresh
  param: { module: investigation, action: update }      

#login
login:
  url:   /login
  param: { module: login, action: login }      

#project site
site_edit:
  url:   /site_edit/:site_id
  param: { module: projectsite, action: edit }

site_list:
  url:   /site_list/*
  param: { module: projectsite, action: list }
  
site_update:
  url:   /site_update
  param: { module: projectsite, action: update }

site_show:
  url:   /site_show/:site_id/*
  param: { module: projectsite, action: show }

#remit
remit_edit:
  url:  /remit_edit/:remit_id
  param: { module: remit, action: edit }  

remit_by_donation:
  url:  /remit_by_donation/:donation_id/*
  param: { module: remit, action: listdonate }  
  
remit_pending:
  url:  /remit_pending/*
  param: { module: remit, action: listpend }  

user_remit_pending:
  url:  /user_remit_pending/*
  param: { module: remit, action: listpenduser }  

remit_show:
  url:  /remit_show/:remit_id/*
  param: { module: remit, action: show }  

remit_update:
  url:  /remit_update
  param: { module: remit, action: update }
  
#reportcard
score_autocomplete:
  url:  /score_autocomplete/:school_id/:site_id/*
  param: { module: reportcard, action: autocomplete}

score_create:
  url:  /score_create/*
  param: { module: reportcard, action: create}

score_edit:
  url:  /score_edit/:report_id
  param: { module: reportcard, action: edit}

score_list_all:
  url:  /score_list_all/*
  param: { module: reportcard, action: listall}

score_i_fill:
  url:  /score_i_fill/*
  param: { module: reportcard, action: listmy}

score_by_student:
  url:  /score_by_student/:student_id/*
  param: { module: reportcard, action: liststu}

score_show:
  url:  /score_show/:report_id/*
  param: { module: reportcard, action: show}

score_update:
  url:  /score_update
  param: { module: reportcard, action: update}
 
 
#school
school_create:
  url:  /school_create/*
  param: { module: school, action: create }

school_edit:
  url:  /school_edit/:school_id
  param: { module: school, action: edit }
  
school_by_site:
  url:  /school_by_site/:site_id/*
  param: { module: school, action: listsite }  
  
school_list:
  url:  /school_list/*
  param: { module: school, action: list }

school_show:
  url:  /school_show/:school_id/*
  param: { module: school, action: show }  
  
#student
student_autocomplete:
  url:  /student_autocomplete/:school_id/:site_id/*
  param: { module: student, action: autocomplete }  

student_cascade:
  url:  /student_cascade
  param: { module: student, action: cascade }  

student_edit:
  url:  /student_edit/:student_id
  param: { module: student, action: edit }

student_list_all:
  url:  /student_list_all/*
  param: { module: student, action: listall }
  
student_need_donate:
  url:  /student_need_donate/*
  param: { module: student, action: listno }

print_table:
  url:  /print_table/:student_id
  param: { module: student, action: print }

student_show:
  url:  /student_show/:student_id/*
  param: { module: student, action: show }
  
student_update:
  url:  /student_update
  param: { module: student, action: update }  
  
#survey
survey_autocomplete:
  url:  /survey_autocomplete/:school_id/:site_id/*
  param: { module: survey, action: autocomplete }
  
survey_cascade2:
  url:  /survey_cascade2
  param: { module: survey, action: cascade2 }
    
survey_cascade:
  url:  /survey_cascade
  param: { module: survey, action: cascade }
  
survey_create:
  url:  /survey_create/*
  param: { module: survey, action: create }

survey_edit:
  url:  /survey_edit/:survey_id
  param: { module: survey, action: edit }  

survey_list_all:
  url:  /survey_list_all/*
  param: { module: survey, action: listall }  

survey_i_fill:
  url:  /survey_i_fill/*
  param: { module: survey, action: listmy }

survey_by_student:
  url:  /survey_by_student/:student_id/*
  param: { module: survey, action: liststu }
  
survey_show:
  url:  /survey_show/:survey_id/*
  param: { module: survey, action: show }

survey_update:
  url:  /survey_update
  param: { module: survey, action: update }

  
#user
user_approve:
  url:  /user_approve
  param: { module: user, action: approve }  

user_create:
  url:  /user_create
  param: { module: user, action: create }

user_edit:
  url:  /user_edit/:user_id
  param: { module: user, action: edit }  

license:
  url:  /license
  param: { module: user, action: license }   
  
all_user:
  url:  /all_user/*
  param: { module: user, action: listall }   

user_show:
  url:  /user_show/:user_id/*
  param: { module: user, action: show }   

user_update:
  url:  /user_update
  param: { module: user, action: update }   
  
user_delete:
  url:  /user_delete/:user_id
  param: { module: user, action: delete }  

# default rules
homepage:
  url:   /
  param: { module: login, action: login }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
