default:
  http_metas:
    content-type: text/html

  metas:
    title:        自由天空
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     zh

  stylesheets:    [main, admin_db, cssMenus]

  javascripts:    []

  has_layout:     on
  layout:         layout
