<?php
// auto-generated by sfPropelCrud
// date: 2009/09/03 02:13:41
?>
<?php use_helper('Object') ?>
<?php use_helper('Javascript')?>
<?php use_helper('Validation')?>
<div class="dparts searchResultList">
<div class="parts">
<div class="partsHeading"><h3><?php if($user->getId()) echo "Edit personal information";else echo "Register"?></h3></div>

<div class="block">
<div class="ditem">
<div class="item">
<?php echo form_tag('user/update','multipart=true') ?>
<?php echo object_input_hidden_tag($user, 'getId') ?>
<?php echo object_input_hidden_tag($user, 'getDroit',0) ?>
<table>
<tbody>
<tr>
  <th>Email*:</th>
  <td><?php echo object_input_tag($user, 'getUsername', array (
  'size' => 20,
)) ?>(Must be ended with "@ericsson.com")<?php echo form_error('username')?>
</td>
</tr>
<tr>
  <th>Nickname*:</th>  
  <td><?php echo object_input_tag($user, 'getNickname', array (
  'size' => 20,
)) ?><?php echo form_error('nickname')?>
</td>
</tr>
<?php if(!$user->getSalt()):?>
<tr>
  <th>Password*:</th>
  <td><?php echo input_password_tag('password')?>(At least 6 chars)</td>
</tr>
<tr>
  <th>Confirm*:</th>
  <td><input type="password" name="password_confirm" id="password_confirm" onChange="checkpassword()" /></td>
</tr>
<?php endif;?>
<tr>
  <th>Name*:</th>
  <td><?php echo object_input_tag($user, 'getName', array (
  'size' => 20,
)) ?><?php echo form_error('name')?></td>
</tr>
<tr>
  <th>Department:</th>
  <td><?php echo select_tag('department_id',objects_for_select($departments,'getId','getTitle',$user->getDepartmentId()))?></td>
</tr>
<tr>
  <th>Photo:</th>
  <td>
  <?php if(!is_null($user->getPhoto())):?>
  <?php echo image_tag('users/'.$user->getPhoto())?>
  <br />
  <?php echo input_file_tag('photo',array('accept'=>'image/*','size'=>'10','style'=>'display:none'))?>
  <?php echo button_to_function('Change','display()',array('id'=>'control_button','size'=>'2'))?>
  <?php else:?>   
  <?php echo input_file_tag('photo',array('accept'=>'image/*','size'=>'10'))?>
  <?php endif;?>(Less than 512KB)
  <?php echo form_error('photo')?>
  </td>
</tr>
<tr>
  <th>Duty:</th>
  <td><?php echo object_input_tag($user, 'getDuty', array (
  'size' => 20,
)) ?><?php echo form_error('duty')?></td>
</tr>
<tr>
  <th>Mobile:</th>
  <td><?php echo object_input_tag($user, 'getMobile', array (
  'size' => 20,
)) ?><?php echo form_error('mobile')?></td>
</tr>
<tr>
  <th>Tel:</th>
  <td><?php echo object_input_tag($user, 'getTel', array (
  'size' => 20,
)) ?><?php echo form_error('tel')?></td>
</tr>
<tr>
  <th>Twitter:</th>
  <td><?php echo object_input_tag($user, 'getTwitter', array (
  'size' => 20,
)) ?><?php echo form_error('twitter')?></td>
</tr>

<tr>
  <th>QQ:</th>
  <td><?php echo object_input_tag($user, 'getQq', array (
  'size' => 20,
)) ?><?php echo form_error('qq')?></td>
</tr>
<tr>
  <th>MSN:</th>
  <td><?php echo object_input_tag($user, 'getMsn', array (
  'size' => 20,
)) ?><?php echo form_error('msn')?></td>
</tr>
</tbody>
</table>
<hr />
<?php if ($user->getId()): ?>
  <?php echo submit_tag('Update') ?>
  &nbsp;<?php echo button_to('cancel', 'user/show?id='.$user->getId()) ?>
<?php else: ?>
<script type="text/javascript">
function checkpassword()
{
	var pass1 = document.getElementById('password').value;
	if(pass1)
	{
		var pass2 = document.getElementById('password_confirm').value;
		if(pass1==pass2&&pass1.match(/([a-zA-Z0-9_]){6}/))
		{
			document.getElementById("submit").disabled="";
		}
		else
		{
			document.getElementById("submit").disabled="disabled";
		}
	}
}
</script>
  <input type="submit" name="submit" id="submit" value="Registered" disabled="disabled" />
    &nbsp;<?php echo button_to('cancel', '@homepage') ?>
<?php endif; ?>
<?php echo "</form>"?>
</div></div></div>
</div><!-- parts -->
</div><!-- dparts -->

