<?php
// auto-generated by sfPropelCrud
// date: 2009/09/03 02:13:41
?>
<?php use_helper('Javascript')?>
<div id="LayoutB" class="Layout">
<div id="Left">
<div class="parts pageNav">
<div class="partsHeading"><h3>Actions</h3></div>
<ul>
<?php if($owner->getId()==$user->getId()):?>
<li><?php echo link_to_remote('Edit information',array('update'=>'Center','url'=>'user/edit'))?></li>
<li><?php echo link_to_remote('Change password',array('update'=>'Center','url'=>'user/change'))?></li>
<?php elseif($owner->getDroit()>=100):?>
<li><?php echo link_to_remote('Assign right',array('update'=>'Center','url'=>'user/admin?id='.$user->getId()))?></li>
<li><?php echo link_to('Delete the user','user/delete?id='.$user->getId(),'post=true&confirm=Are you sure?')?></li>
<?php endif;?>
</ul>
</div>
</div>
<script type="text/javascript">
function checkpassword()
{
	var pass1 = document.getElementById('password').value;
	if(pass1)
	{
		var pass2 = document.getElementById('password_confirm').value;
		if(pass1==pass2)
		{
			document.getElementById("submit").disabled="";
		}
		else
		{
			document.getElementById("submit").disabled="disabled";
		}
	}
}
function checkNum()
{
	var right = document.getElementById('droit').value;
	var obj = document.getElementById('submit');
	if(right.match(/\d{1,3}/))
	{
		 if(right<=100 && right>=0)
		 {
			 obj.disabled = '';
		 }
		 else
		 {
			 obj.disabled = 'disabled';
			 alert('The integer over-ranged.'); 
		 }
	}
	else
	{
		obj.disabled = 'disabled';
		alert('Please input a integer.');		
	}
}
</script>
<div id="Center">
<div class="dparts searchResultList">
<div class="parts">
<div class="partsHeading"><h3>Information</h3></div>

<div class="block">
<div class="ditem">
<div class="item">

<table>
<tbody>
<tr>
<th>Email: </th>
<td><?php echo $user->getUsername() ?></td>
</tr>
<tr>
<th>Nickname: </th>
<td><?php echo $user->getNickname() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $user->getName() ?></td>
</tr>
<tr>
<th>Department: </th>
<td><?php if($user->getDepartment()) echo $user->getDepartment()->getTitle() ?></td>
</tr>
<tr>
<th>Photo: </th>
<td><?php 
    if(!is_null($user->getPhoto()))
      echo image_tag('users/'.$user->getPhoto());
    else
      echo "No image";
    ?></td>
</tr>
<tr>
<th>Duty: </th>
<td><?php echo $user->getDuty() ?></td>
</tr>
<tr>
<th>Mobile: </th>
<td><?php echo $user->getMobile() ?></td>
</tr>
<tr>
<th>Tel: </th>
<td><?php echo $user->getTel() ?></td>
</tr>
<tr>
<th>Twitter: </th>
<td><?php echo $user->getTwitter() ?></td>
</tr>
<tr>
<th>Right: </th>
<td><?php echo $user->getDroit() ?></td>
</tr>
<tr>
<th>Qq: </th>
<td><?php echo $user->getQq() ?></td>
</tr>
<tr>
<th>Msn: </th>
<td><?php echo $user->getMsn() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $user->getCreatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
</div></div></div>
</div><!-- parts -->
</div><!-- dparts -->
</div><!-- Center -->
</div><!-- Layout -->
