<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:34:21
?>
<div id="sf_admin_container">

<h1><?php echo $survey->getStudent()->getName() ?>于
<?php echo $survey->getSurveyDate() ?>
的调查情况</h1>

<?php use_helper('Object') ?>

<div id="sf_admin_content">

<table>
  <tbody>
  <tr>
    <td class="name">调查号：</td>
    <td class="content"><?php echo $survey->getSurveyId() ?></td>
  </tr>
  <tr>
    <td class="name">被调查学生：</td>
    <td class="content"><?php echo $survey->getStudent()->getName() ?></td>
  </tr>
  <tr>
    <td class="name">调查人：</td>
    <td class="content"><?php echo $survey->getUser()->getName() ?></td>
  </tr>   
  <tr>
    <td class="name">调查日期：</td>
    <td class="content"><?php echo $survey->getSurveyDate() ?></td>
  </tr>   
  <tr>
    <td class="name">家庭情况：</td>
    <td class="content"><?php echo $survey->getFamilyCondition() ?></td>
  </tr>   
  <tr>
    <td class="name">年级：</td>
    <td class="content"><?php echo $survey->getGrade() ?></td>
  </tr>
  <tr>
    <td class="name">其他资助情况：</td>
    <td class="content"><?php echo $survey->getOtherAssist() ?></td>
  </tr>
  <tr>
    <td class="name">退学史：</td>
    <td class="content"><?php echo $survey->getDropoutInfo() ?></td>
  </tr>
  <tr>
    <td class="name">自述：</td>
    <td class="content"><?php echo $survey->getPresentation() ?></td>
  </tr>
  <tr>
    <td class="name">年收入：</td>
    <td class="content"><?php echo $survey->getRevenue() ?></td>
  </tr>
  <tr>
    <td class="name">家庭财产：</td>
    <td class="content"><?php echo $survey->getProperty() ?></td>
  </tr>
  <tr>
    <td class="name">捐款用途：</td>
    <td class="content"><?php echo $survey->getDonationUsage() ?></td>
  </tr>
  <tr>
    <td class="name">捐助者关心的问题：</td>
    <td class="content"><?php echo $survey->getDonorConcerned() ?></td>
  </tr>
  <tr>
    <td class="name">给捐助者的话：</td>
    <td class="content"><?php echo $survey->getMsgToDonor() ?></td>
  </tr>
  <tr>
    <td class="name">给学生的话：</td>
    <td class="content"><?php echo $survey->getMsgToStu() ?></td>
  </tr>
  <tr>
    <td class="name">学校意见：</td>
    <td class="content"><?php echo $survey->getSchoolOpinion() ?></td>
  </tr>
  <tr>
    <td class="name">老师意见：</td>
    <td class="content"><?php echo $survey->getTeacherOpinion() ?></td>
  </tr>
  <tr>
    <td class="name">志愿者意见：</td>
    <td class="content"><?php echo $survey->getUserOpinion() ?></td>
  </tr>
  <tr>
    <td class="name">小结：</td>
    <td class="content"><?php echo $survey->getDiscription() ?></td>
  </tr>
  </tbody>
</table>
<?php if ($sf_params->has('after_edit')): ?>
<a href="javascript:history.go(-2)">返回</a>
<?php else:?>
<a href="javascript:history.go(-1)">返回</a>
<?php endif;?>

</div>
</div>