<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:34:38
?>
<div id="sf_admin_container">

<?php if ($user->getUserName()):?>
<h1>修改账户信息</h1>
<?php else:?>
<h1>新建账户</h1>
<?php endif;?>

<?php use_helper('Object') ?>
<?php use_helper('Javascript')?>
<?php use_helper('Validation')?>

<?php echo form_tag('@user_update','multipart=true') ?>

<?php echo object_input_hidden_tag($user, 'getUserId') ?>


<div id="sf_admin_content">

<fieldset id="sf_fieldset_none" class="">

<?php if ( ($sf_user->getAttribute('usertype', '')=='manager') || ($sf_user->getAttribute('usertype', '')=='administrator')):?>
<div class="form-row">
  <label for="user_identity" class="required">批准：</label> 
  <div class="content">
    <?php echo object_checkbox_tag($user, 'getApprove', array (
    'checked' => true 
     )) ?>    
  </div>
</div> 
<?php else:?>
    <?php echo object_input_hidden_tag($user, 'getApprove') ?> 
<?php endif;?> 

<?php if ($user->getUserName()):?>
<div class="form-row">
  <label for="user_username" class="required">用户名：</label> 
  <div class="content">
  <?php echo $user->getUserName();
        echo input_hidden_tag('username', $user->getUserName());  ?>
  </div>
</div>
  
<?php else:?>

<div class="form-row">
  <label for="user_username" class="required">注意：</label> 
  <div class="content">
  完成提交后请耐心等待资格审核，审核成功后方可登录
  </div>
</div>
<?php echo form_error('username')?>
<div class="form-row">
  <label for="user_username" class="required">用户名：</label> 
  <div class="content">
  <?php echo input_tag('username') ?>  
  </div>
</div>
<?php endif;?>
<?php echo form_error('nickname')?>   
<div class="form-row">
  <label for="user_nickname" class="required">昵称：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getNickname', array (
  'size' => 20,
  )) ?>
  </div>
</div>  
<?php echo form_error('sha1_password')?>
<div class="form-row">
  <label for="user_password" class="required">输入新密码：</label> 
  <div class="content">    
  <?php echo input_tag('password');?>
  </div>
</div>  
<?php echo form_error('name')?>
<div class="form-row">
  <label for="user_name" class="required">姓名：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getName', array (
  'size' => 20,
  )) ?>
  </div>
</div>
<?php echo form_error('id_card')?>
<div class="form-row">
  <label for="user_name" class="required">身份证号：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getIdCard', array (
  'size' => 20,
  )) ?>
  </div>
</div>   
<script type="text/javascript">
function display()
{
	var photo_input = document.getElementById("photo");
	var control_button = document.getElementById("control_button");
	var str = control_button.value;
	if(str == "重新上传")
	{
		photo_input.style.display = "inline";
		control_button.value = "取消";
	}
	else
	{
		photo_input.style.display = "none";
		photo_input.value = null;
		control_button.value = "重新上传";
	}	
}
</script>
<?php echo form_error('photo')?>
<div class="form-row">
  <label for="user_photo" class="required">照片：</label> 
  <div class="content">
  <?php if(!is_null($user->getPhoto())):?>
  <?php echo image_tag('users/'.$user->getPhoto())?>
  <?php echo input_file_tag('photo',array('accept'=>'image/*','size'=>'10','style'=>'display:none'))?>
  <?php echo button_to_function('重新上传','display()',array('id'=>'control_button','size'=>'2'))?>
  <?php else:?>   
  <?php echo input_file_tag('photo',array('accept'=>'image/*','size'=>'10'))?>
  <?php endif;?>
  </div>
</div>
<?php echo form_error('bbs_id')?>   
<div class="form-row">
  <label for="user_bbs_id" class="required">BBS 帐号：</label> 
  <div class="content">      
  <?php echo object_input_tag($user, 'getBbsId', array (
  'size' => 20,
  )) ?>
  </div>
</div>  
<?php echo form_error('ofs_id')?>
<div class="form-row">
  <label for="user_ofs_id" class="required">OFS 帐号：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getOfsId', array (
  'size' => 20,
  )) ?>
  </div>
</div>  
<?php echo form_error('create_at')?>
<div class="form-row">
  <label for="user_created_at" class="required">创建日期：</label> 
  <div class="content">    
  <?php echo object_input_date_tag($user, 'getCreatedAt', array (
  'rich' => true,
  'withtime' => true,
  )) ?>
  </div>
</div> 
<?php echo form_error('mobile')?>
<div class="form-row">
  <label for="user_mobile" class="required">移动电话：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getMobile', array (
  'size' => 20,
  )) ?>
  </div>
</div>  
<?php echo form_error('tel')?>
<div class="form-row">
  <label for="user_tel" class="required">固定电话：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getTel', array (
  'size' => 20,
  )) ?>
  </div>
</div>  
<div class="form-row">
  <label for="user_role" class="required">权限：</label> 
  <div class="content">    
  <?php
     if ( ($sf_user->getAttribute('usertype', '')=='manager') || ($sf_user->getAttribute('usertype', '')=='administrator'))
     {
        echo select_tag('usertype', options_for_select(array(
                     'volunteer'  => '普通志愿者',
                     'surveyor'   => '调查员',
                     'manager'    => '管理员',
                    ), $user->getUsertype()));
     }
     else if ($sf_user->getAttribute('usertype', '')=='surveyor')
     {
        echo '调查员';
        echo object_input_hidden_tag($user, 'getUsertype');	
     }
     else
     {
        echo input_hidden_tag('usertype', 'volunteer');
        echo '普通志愿者';
     }
  ?>

  </div>
</div>  
<?php if ( ($sf_user->getAttribute('usertype', '')=='manager') || ($sf_user->getAttribute('usertype', '')=='administrator')):?>

<?php echo form_error('identity')?>
<div class="form-row">
  <label for="user_identity" class="required">身份：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getIdentity', array (
  'size' => 7,
  )) ?>
  </div>
</div>
<?php echo form_error('duty')?>
<div class="form-row">
  <label for="user_duty" class="required">职务：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getDuty', array (
  'size' => 70,
  )) ?>
  </div>
</div>

<?php else:?>
<?php endif;?>    
<?php echo form_error('email')?>  
<div class="form-row">
  <label for="user_email" class="required">Email：</label> 
  <div class="content">      
  <?php echo object_input_tag($user, 'getEmail', array (
  'size' => 32,
  )) ?>
  </div>
</div>  
<?php echo form_error('qq')?>
<div class="form-row">
  <label for="user_qq" class="required">QQ：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getQq', array (
  'size' => 32,
  )) ?>
  </div>
</div>  
<?php echo form_error('msn')?>
<div class="form-row">
  <label for="user_msn" class="required">Msn：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getMsn', array (
  'size' => 32,
  )) ?>
  </div>
</div>  
<?php echo form_error('address')?>
<div class="form-row">
  <label for="user_address" class="required">地址：</label> 
  <div class="content">    
  <?php echo object_input_tag($user, 'getAddress', array (
  'size' => 70,
  )) ?>
  </div>
</div>  
</fieldset>

<?php echo submit_tag('提交') ?>

&nbsp;&nbsp;&nbsp;<a href="javascript:history.go(-1)">返回</a>
</form>
</div>
</div>

