<?php
// auto-generated by sfPropelCrud
// date: 2009/09/03 02:13:30
?>
<?php use_helper('Object') ?>
<?php use_helper('Validation')?>
<div id="LayoutC" class="Layout">
<div id="Center">
<div class="dparts searchResultList">
<div class="parts">
<div class="partsHeading"><h3>Publish Topic</h3></div>

<div class="block">
<div class="ditem">
<div class="item">
<?php echo form_tag('topic/update') ?>
<?php echo object_input_hidden_tag($topic, 'getId') ?>
<?php echo object_input_hidden_tag($topic, 'getDepartmentId') ?>
<table>
<tbody>
<tr>
  <th>Title*:</th>
  <td><?php echo object_input_tag($topic, 'getTitle', array (
  'size' => 32,
)) ?><?php echo form_error('title')?></td>
</tr>
<tr>
  <th>Content*:</th>
  <td><?php $options = array(
	'rich' => 'fck',
	'height' => 500,
	'width'	=> 528,
    'tool'  => 'QQchong',
);
echo textarea_tag('content', $topic->getContent(), $options ); 
  ?>
  <?php echo form_error('content')?>
  </td>
</tr>
</tbody>
</table>
<hr />
<?php if ($topic->getId()): ?>
<?php echo submit_tag('save') ?>
<?php echo button_to('cancel', 'topic/show?id='.$topic->getId()) ?>
<?php else: ?>
<?php echo submit_tag('Publish') ?>
<?php echo button_to('cancel', 'topic/list?dpt_id='.$topic->getDepartmentId()) ?>
<?php endif; ?>
<?php echo "</form>"?>
</div></div></div>
</div><!-- parts -->
</div><!-- dparts -->
</div><!-- Center -->
</div><!-- Layout -->
