<?php
// auto-generated by sfPropelCrud
// date: 2009/07/17 09:11:36
?>
<?php use_helper('Text') ?>
<div id="sf_admin_container">
<h1>newps</h1>

<div id="sf_admin_content">
<table cellspacing="0" class="sf_admin_list">
<thead>
<tr>
  <th>站点</th>
  <th>站点名</th>
  <th>省</th>
  <th>城市</th>
  <th>区</th>
  <th>简介</th>
  <th>地区学校</th>
</tr>
</thead>
<tbody>
<?php $count_row = 0?>
<?php foreach ($project_sites as $project_site): ?>

  <?php echo "<tr class='sf_admin_row_".$count_row."' >" ?>
    <td width="10%"><?php echo link_to($project_site->getSiteId(), 'projectsite/show?site_id='.$project_site->getSiteId()) ?></td>
    <td width="10%"><?php echo $project_site->getSiteName() ?></td>
    <td width="10%"><?php echo $project_site->getProvince() ?></td>
    <td width="10%"><?php echo $project_site->getCity() ?></td>
    <td width="10%"><?php echo $project_site->getDistrict() ?></td>
    <td width="40%" class="discription"><?php echo truncate_text(strip_tags($project_site->getDiscription()), 200) ?></td>
    <td width="10%"><?php echo link_to('查看该地区学校', 'school/list?site_id='.$project_site->getSiteId()) ?></td> 
  <?php
    if($count_row)
       $count_row = 0;
    else
       $count_row = 1;
  ?>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'projectsite/create') ?>
</div>

</div>