<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:32:17
?>
<div id="sf_admin_container">
<h1>待审批资助</h1>

<?php if(sizeof($pager->getResults()) != 0):?>
<div id="sf_admin_content">
<table cellspacing="0" class="sf_admin_list">

<thead>
<tr>
  <th>学生</th>
  <th>资助状态</th>
  <th>申请捐助人</th>
  <th>捐助金额</th>
  <th>开始资助于</th>
  <th>终止资助于</th>
  <th>已批准</th>
  <th>已进行</th>  
  <th>提交于</th>
  <th>操作</th>
</tr>
</thead>
<tbody>
<?php $count_row = 0?>
<?php foreach ($pager->getResults() as $donation): ?>

  <?php echo "<tr class='sf_admin_row_".$count_row."' >" ?>      
      <td><?php echo $donation->getStudent()->getName() ?></td>
      <td><?php 
             if($donation->getStudent()->getIsDonated())
             { 
                echo image_tag('admin_db/x.png');
             	echo '有人资助！<br/>不能审批';
             } 
             else
             {
             	echo image_tag('admin_db/tick.png');
             	echo '可以审批';
             }
          ?></td>
      <td><?php echo $donation->getUser()->getName() ?></td>
      <td><?php echo $donation->getAmount() ?></td>      
      <td><?php echo $donation->getStartDate() ?></td>
      <td><?php echo $donation->getEndDate() ?></td>
      <td><?php if ($donation->getApprove()) echo image_tag('admin_db/tick.png'); else echo image_tag('admin_db/x.png'); ?></td>
      <td><?php if ($donation->getIsActive()) echo image_tag('admin_db/tick.png'); else echo image_tag('admin_db/x.png'); ?></td>
      <td><?php echo $donation->getCreatedAt() ?></td>
      <td><?php echo link_to('查看', '@donation_show?donation_id='.$donation->getDonationId())?>&nbsp;&nbsp;&nbsp;
          <?php if (!($donation->getStudent()->getIsDonated())) 
                     echo link_to('批复', '@donation_edit?donation_id='.$donation->getDonationId());
          ?>&nbsp;&nbsp;&nbsp;
          <?php echo link_to('删除', 'donation/delete?donation_id='.$donation->getDonationId(), 'post=true&confirm=真的要删除么？') ?>
      </td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php include_partial('pager',array('pager' => $pager, 'page_to_link' => '@donation_approve' ))?>

<?php else:?>
无相关记录<br/>
<?php endif;?>


</div>
</div>
