<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:32:17
?>
<div id="sf_admin_container">
<h1>捐助信息</h1>

<?php if(sizeof($pager->getResults()) != 0):?>
<div id="sf_admin_content">
<table cellspacing="0" class="sf_admin_list">

<thead>
<tr>
  <th>捐助号</th>
  <th>学生姓名</th>
  <th>捐助人姓名</th>
  <th>捐助金额</th>
  <th>开始资助于</th>
  <th>终止资助于</th>
  <th>已批准</th>
  <th>进行中</th>  
  <th>提交于</th>
  <th>到款信息</th>
  <th>操作</th>
</tr>
</thead>
<tbody>
<?php $count_row = 0?>
<?php foreach ($pager->getResults() as $donation): ?>

  <?php echo "<tr class='sf_admin_row_".$count_row."' >" ?>
      <td><?php echo link_to($donation->getDonationId(), '@donation_show?donation_id='.$donation->getDonationId()) ?></td>
      <td><?php echo $donation->getStudent()->getName() ?></td>
      <td><?php echo $donation->getUser()->getName() ?></td>
      <td><?php echo $donation->getAmount() ?></td>      
      <td><?php echo $donation->getStartDate() ?></td>
      <td><?php echo $donation->getEndDate() ?></td>
      <td><?php if ($donation->getApprove()) echo image_tag('admin_db/tick.png'); else echo image_tag('admin_db/x.png'); ?></td>
      <td><?php if ($donation->getIsActive()) echo image_tag('admin_db/tick.png'); else echo image_tag('admin_db/x.png'); ?></td>
      <td><?php echo $donation->getCreatedAt() ?></td>
      <td><?php if ($donation->getApprove() || $donation->getIsActive())echo link_to ('查看', '@remit_by_donation?donation_id='.$donation->getDonationId(),'post=true') ?></td>
      <td><?php echo link_to('详情', '@donation_show?donation_id='.$donation->getDonationId(),'post=true')?>&nbsp;
          <?php if (($sf_user->getAttribute('user_id', '')==$donation->getUserId())||($sf_user->getAttribute('usertype', '')=='administrator') || ($sf_user->getAttribute('usertype', '')=='manager'))
                {
                   echo link_to('修改', '@donation_edit?donation_id='.$donation->getDonationId(),'post=true');
                } 
          ?>
          &nbsp;
          <?php if (($sf_user->getAttribute('usertype', '')=='administrator') || ($sf_user->getAttribute('usertype', '')=='manager'))
                {  
                   echo link_to('删除', 'donation/delete?donation_id='.$donation->getDonationId(), 'post=true&confirm=真的要删除么？');
                }
          ?>
      </td> 
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php $donations = $pager->getResults()?>
<?php if ($pager->haveToPaginate()): ?>
  <?php echo link_to(image_tag('admin_db/first.png'), '@donation_student?page='.$pager->getFirstPage().'&student_id='.$donations[0]->getStudentId()) ?>
  <?php echo link_to(image_tag('admin_db/previous.png'), '@donation_student?page='.$pager->getPreviousPage().'&student_id='.$donations[0]->getStudentId()) ?>
  <?php $links = $pager->getLinks(); foreach ($links as $page): ?>
    <?php echo ($page == $pager->getPage()) ? $page : link_to($page, '@donation_student?page='.$page.'&student_id='.$donations[0]->getStudentId()) ?>
    <?php if ($page != $pager->getCurrentMaxLink()): ?><?php endif ?>
  <?php endforeach ?>
  <?php echo link_to(image_tag('admin_db/next.png'), '@donation_student?page='.$pager->getNextPage().'&student_id='.$donations[0]->getStudentId()) ?>
  <?php echo link_to(image_tag('admin_db/last.png'), '@donation_student?page='.$pager->getLastPage().'&student_id='.$donations[0]->getStudentId()) ?>
  <?php echo $pager->getNbResults() ?> results found.<br />
  Displaying results <?php echo $pager->getFirstIndice() ?> to  <?php echo $pager->getLastIndice() ?>.<br/>

  <?php echo form_tag('@donation_student?student_id='.$donations[0]->getStudentId())?>
  Jump to Page <?php echo input_tag('page', 1, 'size=2' )?>
  
  <?php echo submit_tag('Go!')?>
  </form>
<?php endif ?><br/>

<?php else:?>
无相关记录<br/>
<?php endif;?>

<?php echo link_to('新建资助','@donation_create?student_id='.$sf_params->get('student_id'));?>
&nbsp;&nbsp;&nbsp;<a href="javascript:history.go(-1)">返回</a>
</div>
</div>
