<?php
// auto-generated by sfPropelCrud
// date: 2009/07/22 06:54:58
?>
<?php

/**
 * school actions.
 *
 * @package    donate
 * @subpackage school
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class schoolActions extends sfActions
{
	public function executeIndex()
	{
		return $this->forward('school', 'list');
	}

	public function executeList()
	{
		$c = new Criteria();
		if ($this->getRequestParameter('site_id'))
		{
			$c -> add(SchoolPeer::SITE_ID, $this->getRequestParameter('site_id'));
		}
		$this->schools = SchoolPeer::doSelect($c);
	}

	public function executeShow()
	{
		$this->school = SchoolPeer::retrieveByPk($this->getRequestParameter('school_id'));
		$this->forward404Unless($this->school);
	}

	public function executeCreate()
	{
		$this->school = new School();

		$this->setTemplate('edit');
	}

	public function executeEdit()
	{
		$this->school = SchoolPeer::retrieveByPk($this->getRequestParameter('school_id'));
		$this->forward404Unless($this->school);
	}

	public function executeUpdate()
	{
		if (!$this->getRequestParameter('school_id'))
		{
			$school = new School();
		}
		else
		{
			$school = SchoolPeer::retrieveByPk($this->getRequestParameter('school_id'));
			$this->forward404Unless($school);
		}

		$school->setSchoolId($this->getRequestParameter('school_id'));
		$school->setSiteId($this->getRequestParameter('site_id') ? $this->getRequestParameter('site_id') : null);
		$school->setSchoolName($this->getRequestParameter('school_name'));
		$school->setType($this->getRequestParameter('type'));
		$school->setMaster($this->getRequestParameter('master'));
		$school->setContact($this->getRequestParameter('contact'));
		$school->setPhone($this->getRequestParameter('phone'));
		$school->setAddress($this->getRequestParameter('address'));
		$school->setPostal($this->getRequestParameter('postal'));
		$school->setDiscription($this->getRequestParameter('discription'));

		$school->save();

		return $this->redirect('school/show?school_id='.$school->getSchoolId());
	}

	public function executeDelete()
	{
		$school = SchoolPeer::retrieveByPk($this->getRequestParameter('school_id'));

		$this->forward404Unless($school);

		$school->delete();

		return $this->redirect('school/list');
	}
}
