<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:33:53
?>
<div id="sf_admin_container">
<h1>学校信息</h1>

<div id="sf_admin_content">
<table cellspacing="0" class="sf_admin_list">

<thead>
<tr>
  <th>学校号</th>
  <th>资助点</th>
  <th>学校名</th>
  <th>类型</th>
  <th>校长</th>
  <th>联系人</th>
  <th>电话</th>
  <th>地址</th>
  <th>邮政编码</th>
  <th>简介</th>
</tr>
</thead>
<tbody>
<?php $count_row = 0?>
<?php foreach ($schools as $school): ?>

  <?php echo "<tr class='sf_admin_row_".$count_row."' >" ?>
    <td><?php echo link_to($school->getSchoolId(), 'school/show?school_id='.$school->getSchoolId()) ?></td>
      <td><?php echo $school->getSiteId() ?></td>
      <td><?php echo $school->getSchoolName() ?></td>
      <td><?php echo $school->getType() ?></td>
      <td><?php echo $school->getMaster() ?></td>
      <td><?php echo $school->getContact() ?></td>
      <td><?php echo $school->getPhone() ?></td>
      <td><?php echo $school->getAddress() ?></td>
      <td><?php echo $school->getPostal() ?></td>
      <td><?php echo $school->getDiscription() ?></td>
  <?php
    if($count_row)
       $count_row = 0;
    else
       $count_row = 1;
  ?>         
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'school/create') ?>
</div>
</div>