<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:33:07
?>
<div id="sf_admin_container">

<h1>汇款信息</h1>

<?php use_helper('Object') ?>

<?php echo form_tag('remit/update') ?>

<?php echo object_input_hidden_tag($remit, 'getRemitId') ?>
<?php echo object_input_hidden_tag($remit, 'getDonationId') ?>

<div id="sf_admin_content">

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <label for="remit_donation_id" class="required">捐助号：</label> 
  <div class="content">
  <?php echo $remit->getDonationID()?>
  </div>
</div>  
  
<div class="form-row">
  <label for="remit_amount" class="required">金额：</label> 
  <div class="content">  
  <?php echo object_input_tag($remit, 'getAmount', array (
  'size' => 7,
  )) ?>
  </div>
</div>   

<?php 
      $flag_by_ofs = 0;
      if ($sf_params->has('is_by_ofs'))
      {
         if ($sf_params->get('is_by_ofs'))
         {
            $flag_by_ofs = 1;
         }
      }  
      else
      {
         if ($remit->getIsByOfs())
         {
            $flag_by_ofs = 1;
         }
      }
?>

<?php if ($flag_by_ofs):?>

<?php echo input_hidden_tag('is_by_ofs', 1) ?>
<div class="form-row">
  <label for="remit_is_ceived" class="required">已收到：</label> 
  <div class="content">   
  <?php echo object_checkbox_tag($remit, 'getIsReceived', array (
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="remit_receive_date" class="required">收款日期：</label> 
  <div class="content">   
  <?php echo object_input_date_tag($remit, 'getReceiveDate', array (
    'rich' => true,
  )) ?>
  </div>
</div>   

<div class="form-row">
  <label for="remit_receive_user_id" class="required">收款人：</label> 
  <div class="content">   
  <?php echo object_select_tag($remit, 'getReceiveUserId', array (
    'related_class' => 'User',
    'include_blank' => true,
  )) ?>
  </div>
</div>   

<div class="form-row">
  <label for="remit_is_sendout" class="required">已发出：</label> 
  <div class="content">   
  <?php echo object_checkbox_tag($remit, 'getIsSendout', array (
  )) ?>
  </div>
</div>  
  
<div class="form-row">
  <label for="remit_sendout_date" class="required">发款日期：</label> 
  <div class="content">   
  <?php echo object_input_date_tag($remit, 'getSendoutDate', array (
    'rich' => true,
  )) ?>
  </div>
</div>   

<div class="form-row">
  <label for="remit_sendout_user_id" class="required">发款人：</label> 
  <div class="content">   
  <?php echo object_select_tag($remit, 'getSendoutUserId', array (
    'related_class' => 'User',
    'include_blank' => true,
  )) ?>
  </div>
</div>  

<?php else:?>

<?php echo input_hidden_tag('is_by_ofs', 0) ?>
<div class="form-row">
  <label for="remit_is_sendout" class="required">已发出：</label> 
  <div class="content">   
  <?php echo object_checkbox_tag($remit, 'getIsSendout', array (
  )) ?>
  </div>
</div>  
  
<div class="form-row">
  <label for="remit_sendout_date" class="required">发款日期：</label> 
  <div class="content">   
  <?php echo object_input_date_tag($remit, 'getSendoutDate', array (
    'rich' => true,
  )) ?>
  </div>
</div>   

<?php endif;?>
</fieldset>

<?php echo submit_tag('提交') ?>
<?php if ($remit->getRemitId()): ?>
  &nbsp;<?php echo link_to('删除', 'remit/delete?remit_id='.$remit->getRemitId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('返回', 'remit/show?remit_id='.$remit->getRemitId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('返回', 'remit/list') ?>
<?php endif; ?>
</form>
</div>
</div>