<?php
// auto-generated by sfPropelCrud
// date: 2009/09/03 02:12:21
?>
<?php use_helper('Object') ?>
<?php use_helper('Validation')?>
<?php echo form_tag('blog/update') ?>

<?php echo object_input_hidden_tag($blog, 'getId') ?>
<div id="LayoutC" class="Layout">
<div id="Center">
<div class="dparts searchResultList">
<div class="parts">
<div class="partsHeading"><h3>Post a blog</h3></div>

<div class="block">
<div class="ditem">
<div class="item">

<table>
<tbody>
<tr>
  <th>Title*:</th>
  <td><?php echo object_input_tag($blog, 'getTitle', array (
  'size' => 20,
)) ?><?php echo form_error('title')?></td>
</tr>
<tr>
  <th>Content*:</th>
  <td>
  <?php $options = array(
	'rich' => 'fck',
	'height' => 500,
	'width'	=> 528,
    'tool'  => 'QQchong',
);
echo textarea_tag('content', $blog->getContent(), $options ); 
  ?>
<?php echo form_error('content')?>
</td>
</tr>
<!--  
<tr>
  <th>Recommend:</th>
  <td><?php echo object_input_tag($blog, 'getRecommend', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Rdtime:</th>
  <td><?php echo object_input_date_tag($blog, 'getRdtime', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
-->
</tbody>
</table>
<hr />
<?php if ($blog->getId()): ?>
  <?php echo submit_tag('Save')?>
  <?php echo button_to('Cancel', 'blog/show?id='.$blog->getId()) ?>
<?php else: ?>
  <?php echo submit_tag('Publish') ?>
  <?php echo button_to('Cancel', 'blog/list') ?>
<?php endif; ?>
<?php echo "</form>"?>

</div></div></div>
</div><!-- parts -->
</div><!-- dparts -->
</div><!-- Center -->
</div><!-- Layout -->

