<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:34:06
?>
<div id="sf_admin_container">

<h1>学生信息</h1>

<?php use_helper('Object') ?>
<?php use_helper('Javascript')?>

<?php echo form_tag('student/update','multipart=true') ?>

<?php echo object_input_hidden_tag($student, 'getStudentId') ?>

<div id="sf_admin_content">

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <label for="student_school_id" class="required">学校号：</label> 
  <div class="content">   
  <?php echo object_select_tag($student, 'getSchoolId', array (
  'related_class' => 'School',
  )) ?>
  </div>
</div> 

<div class="form-row">
  <label for="student_student_name" class="required">姓名：</label> 
  <div class="content">     
  <?php echo object_input_tag($student, 'getName', array (
  'size' => 20,
  )) ?>
  </div>
</div>  
  
<div class="form-row">
  <label for="student_nick_name" class="required">昵称：</label> 
  <div class="content">     
  <?php echo object_input_tag($student, 'getNickname', array (
  'size' => 20,
  )) ?>
  </div>
</div>  
<script type="text/javascript">
function display()
{
	var photo_input = document.getElementById("photo");
	var control_button = document.getElementById("control_button");
	var str = control_button.value;
	if(str == "重新上传")
	{
		photo_input.style.display = "inline";
		control_button.value = "取消";
	}
	else
	{
		photo_input.style.display = "none";
		photo_input.value = null;
		control_button.value = "重新上传";
	}	
}
</script>
<div class="form-row">
  <label for="student_photo" class="required">照片：</label> 
  <div class="content">
  <?php if(!is_null($student->getPhoto())):?>
  <?php echo image_tag('students/'.$student->getPhoto())?>
  <?php echo input_file_tag('photo',array('accept'=>'image/*','size'=>'10','style'=>'display:none'))?>
  <?php echo button_to_function('重新上传','display()',array('id'=>'control_button','size'=>'2'))?>
  <?php else:?>   
  <?php echo input_file_tag('photo',array('accept'=>'image/*','size'=>'10'))?>
  <?php endif;?>
  </div>
</div>  

<div class="form-row">
  <label for="student_head_teacher" class="required">班主任：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getHeadTeacher', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_guardian" class="required">监护人：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getGuardian', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_birthday" class="required">生日：</label> 
  <div class="content">   
  <?php echo object_input_date_tag($student, 'getBirthday', array (
  'rich' => true,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_grade" class="required">年级：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getGrade', array (
  'size' => 7,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_male" class="required">男？：</label> 
  <div class="content">   
  <?php echo object_checkbox_tag($student, 'getMale', array (
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_address" class="required">住址：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getAddress', array (
  'size' => 80,
  )) ?>
  </div>
</div>  
  
<div class="form-row">
  <label for="student_address" class="required">邮编：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getPostal', array (
  'size' => 20,
  )) ?>
  </div>
</div>
  
<div class="form-row">
  <label for="student_city" class="required">城市：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getCity', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_province" class="required">省：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getProvince', array (
  'size' => 20,
  )) ?>
  </div>
</div>

<div class="form-row">
  <label for="student_assist_history" class="required">资助史：</label> 
  <div class="content">   
  <?php echo object_textarea_tag($student, 'getAssistHistory', array (
  'size' => '30x3',
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_is_in_study" class="required">在学：</label> 
  <div class="content">   
  <?php echo object_checkbox_tag($student, 'getIsInstudy', array (
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_is_boarder" class="required">寄宿生：</label> 
  <div class="content">   
  <?php echo object_checkbox_tag($student, 'getIsBoarder', array (
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_dropout_history" class="required">有无退学史：</label> 
  <div class="content">   
  <?php echo object_checkbox_tag($student, 'getHasDropoutHistory', array (
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_term_expense" class="required">学期花费：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getTermExpense', array (
  'size' => 7,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_discription" class="required">自述：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getDiscription', array (
   
  )) ?>
  </div>
</div>  

<br/>
<h2>亲属1</h2> 

<div class="form-row">
  <label for="student_fm1_relation" class="required">关系：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getFm1Relation', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_fm1_name" class="required">姓名：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getFm1Name', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_fm1_age" class="required">年龄：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getFm1Age', array (
  'size' => 7,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_fm1_occupation" class="required">职业：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getFm1Occupation', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_fm1_discription" class="required">简介</label> 
  <div class="content">     
  <?php echo object_input_tag($student, 'getFm1Discription', array (
   
  )) ?>
  </div>
</div>  

<br/>
<h2>亲属2</h2> 
<div class="form-row">
  <label for="student_fm2_relation" class="required">关系：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getFm2Relation', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_fm2_name" class="required">姓名：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getFm2Name', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_fm2_age" class="required">年龄：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getFm2Age', array (
  'size' => 7,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_fm2_occupation" class="required">职业：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getFm2Occupation', array (
  'size' => 20,
  )) ?>
  </div>
</div>  
  
<div class="form-row">
  <label for="student_fm2_discription" class="required">简介</label> 
  <div class="content">     
  <?php echo object_input_tag($student, 'getFm2Discription', array (
   
  )) ?>
  </div>
</div>  

<br/>
<h2>亲属3</h2> 

<div class="form-row">
  <label for="student_fm3_relation" class="required">关系：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getFm3Relation', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_fm3_name" class="required">姓名：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getFm3Name', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_fm3_age" class="required">年龄：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getFm3Age', array (
  'size' => 7,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_fm3_occupation" class="required">职业：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getFm3Occupation', array (
  'size' => 20,
  )) ?>
  </div>
</div>  
  
<div class="form-row">
  <label for="student_fm3_discription" class="required">简介</label> 
  <div class="content">     
  <?php echo object_input_tag($student, 'getFm3Discription', array (
   
  )) ?>
  </div>
</div>  

<br/>
<h2>亲属4</h2> 

<div class="form-row">
  <label for="student_fm4_relation" class="required">关系：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getFm4Relation', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_fm4_name" class="required">姓名：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getFm4Name', array (
  'size' => 20,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_fm4_age" class="required">年龄：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getFm4Age', array (
  'size' => 7,
  )) ?>
  </div>
</div>  

<div class="form-row">
  <label for="student_fm4_occupation" class="required">职业：</label> 
  <div class="content">   
  <?php echo object_input_tag($student, 'getFm4Occupation', array (
  'size' => 20,
  )) ?>
  </div>
</div>  
  
<div class="form-row">
  <label for="student_fm4_discription" class="required">简介</label> 
  <div class="content">     
  <?php echo object_input_tag($student, 'getFm4Discription', array (
   
  )) ?>
  </div>
</div>
  
</fieldset>
<?php echo submit_tag('提交') ?>

&nbsp;&nbsp;&nbsp;<a href="javascript:history.go(-1)">返回</a>
</form>
</div>
</div>