<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:34:06
?>
<div id="sf_admin_container">

<h1>学生信息</h1>




<table>
<tbody>
<tr>
<td colspan=2>
<table>
  <tbody>

  <tr>
    <td class="name">学校：</td>
    <td class="content"><?php echo $student->getSchool()->getSchoolName() ?></td>
  </tr>
  <tr>
    <td class="name">姓名：</td>
    <td class="content"><?php echo $student->getName() ?></td>
  </tr>
  <tr>
    <td class="name">昵称：</td>
    <td class="content"><?php echo $student->getNickname() ?></td>
  </tr>                
  <tr>
    <td class="name">照片：</td>
    <td class="content">
    <?php 
    if(!is_null($student->getPhoto()))
      echo image_tag('students/'.$student->getPhoto());
    else
      echo "暂未上传照片";
    ?>
    </td>
  </tr>    
  <tr>
    <td class="name">班主任：</td>
    <td class="content"><?php echo $student->getHeadTeacher() ?></td>
  </tr>
  <tr>
    <td class="name">监护人：</td>
    <td class="content"><?php echo $student->getGuardian() ?></td>
  </tr>
  <tr>
    <td class="name">生日：</td>
    <td class="content"><?php echo $student->getBirthday() ?></td>
  </tr>
  <tr>
    <td class="name">年级：</td>
    <td class="content"><?php echo $student->getGrade() ?></td>
  </tr>
  <tr>
    <td class="name">性别：</td>
    <td class="content">
    <?php
       if ($student->getMale())       
         echo '男';
      else
         echo '女';       
    ?>
    </td>
  </tr>                            
  <tr>
    <td class="name">地址：</td>
    <td class="content"><?php echo $student->getAddress() ?></td>
  </tr>
  <tr>
    <td class="name">邮编：</td>
    <td class="content"><?php if ($student->getPostal()) echo $student->getPostal(); ?></td>
  </tr>          
  <tr>
    <td class="name">城市：</td>
    <td class="content"><?php echo $student->getCity() ?></td>
  </tr>    
  <tr>
    <td class="name">省：</td>
    <td class="content"><?php echo $student->getProvince() ?></td>
  </tr>
  <tr>
    <td class="name">资助历史：</td>
    <td class="content"><?php echo $student->getAssistHistory() ?></td>
  </tr>
  <tr>
    <td class="name">上学中：</td>
    <td class="content">
    <?php if($student->getIsInStudy()) echo image_tag('admin_db/tick.png'); else echo image_tag('admin_db/x.png');?>
    </td>
  </tr>
  <tr>
    <td class="name">寄宿生：</td>
    <td class="content">
    <?php if($student->getIsBoarder()) echo image_tag('admin_db/tick.png'); else echo image_tag('admin_db/x.png');?>
    </td>
  </tr>
  <tr>
    <td class="name">有退学史：</td>
    <td class="content">
    <?php  echo $student->getDropoutHistory()?>
    </td>
  </tr>
  <tr>
    <td class="name">学期花费：</td>
    <td class="content"><?php if ($student->getTermExpense()) echo $student->getTermExpense(); ?></td>
  </tr>
  <tr>
    <td class="name">个人简介：</td>
    <td class="content"><?php echo $student->getDiscription() ?></td>
  </tr>
  <tbody>
</table>
</td>
</tr>
<tr>
<td>
<h2>亲属1</h2>                                           
<table>
  <tbody>
  <tr>
    <td class="name">关系：</td>
    <td class="content"><?php echo $student->getFm1Relation() ?></td>
  </tr>
  <tr>
    <td class="name">姓名：</td>
    <td class="content"><?php echo $student->getFm1Name() ?></td>
  </tr>
  <tr>
    <td class="name">年龄：</td>
    <td class="content"><?php if ($student->getFm1Age()) echo $student->getFm1Age(); ?></td>
  </tr>
  <tr>
    <td class="name">职业：</td>
    <td class="content"><?php echo $student->getFm1Occupation() ?></td>
  </tr>
  <tr>
    <td class="name">简介：</td>
    <td class="content"><?php echo $student->getFm1Discription() ?></td>
  </tr>
  </tbody>
</table>
</td>
<td>
<h2>亲属2</h2>                                           
<table>
  <tbody>
  <tr>
    <td class="name">关系：</td>
    <td class="content"><?php echo $student->getFm2Relation() ?></td>
  </tr>
  <tr>
    <td class="name">姓名：</td>
    <td class="content"><?php echo $student->getFm2Name() ?></td>
  </tr>
  <tr>
    <td class="name">年龄：</td>
    <td class="content"><?php if($student->getFm2Age()) echo $student->getFm2Age(); ?></td>
  </tr>
  <tr>
    <td class="name">职业：</td>
    <td class="content"><?php echo $student->getFm2Occupation() ?></td>
  </tr>
  <tr>
    <td class="name">简介：</td>
    <td class="content"><?php echo $student->getFm2Discription() ?></td>
  </tr>
  </tbody>
</table>
</td>
</tr>
<tr>
<td>
<h2>亲属3</h2>                                           
<table>
  <tbody>
  <tr>
    <td class="name">关系：</td>
    <td class="content"><?php echo $student->getFm3Relation() ?></td>
  </tr>
  <tr>
    <td class="name">姓名：</td>
    <td class="content"><?php echo $student->getFm3Name() ?></td>
  </tr>
  <tr>
    <td class="name">年龄：</td>
    <td class="content"><?php if ($student->getFm3Age()) echo $student->getFm3Age(); ?></td>
  </tr>
  <tr>
    <td class="name">职业：</td>
    <td class="content"><?php echo $student->getFm3Occupation() ?></td>
  </tr>
  <tr>
    <td class="name">简介：</td>
    <td class="content"><?php echo $student->getFm3Discription() ?></td>
  </tr>
  </tbody>
</table>
</td>
<td>
<h2>亲属4</h2>                                           
<table>
  <tbody>
  <tr>
    <td class="name">关系：</td>
    <td class="content"><?php echo $student->getFm4Relation() ?></td>
  </tr>
  <tr>
    <td class="name">姓名：</td>
    <td class="content"><?php echo $student->getFm4Name() ?></td>
  </tr>
  <tr>
    <td class="name">年龄：</td>
    <td class="content"><?php if ($student->getFm4Age()) echo $student->getFm4Age(); ?></td>
  </tr>
  <tr>
    <td class="name">职业：</td>
    <td class="content"><?php echo $student->getFm4Occupation() ?></td>
  </tr>
  <tr>
    <td class="name">简介：</td>
    <td class="content"><?php echo $student->getFm4Discription() ?></td>
  </tr>
  </tbody>
</table>
</td>
</tr>
</tbody>
</table>

<?php if(sizeof($donations) != 0 ): ?>
<table>
<thead>
<tr>
  <th>Donation</th>
  <th>Student</th>
  <th>User</th>
  <th>Amount</th>
  <th>Start date</th>
  <th>End date</th>
  <th>Approve</th>
  <th>Is active</th>
  <th>Created at</th>
</tr>
</thead>
<tbody>
<?php foreach ($donations as $donation): ?>
<tr>
    <td><?php echo link_to($donation->getDonationId(), 'aaa/show?donation_id='.$donation->getDonationId()) ?></td>
      <td><?php echo $donation->getStudentId() ?></td>
      <td><?php echo $donation->getUserId() ?></td>
      <td><?php echo $donation->getAmount() ?></td>
      <td><?php echo $donation->getStartDate() ?></td>
      <td><?php echo $donation->getEndDate() ?></td>
      <td><?php echo $donation->getApprove() ?></td>
      <td><?php echo $donation->getIsActive() ?></td>
      <td><?php echo $donation->getCreatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php else:?>
无资助记录<br/>
<?php endif;?>

<?php if($survey == null): ?>
无调查记录<br/>
<?php else:?>
<table>
<tbody>
<tr>
<th>Survey: </th>
<td><?php echo $survey->getSurveyId() ?></td>
</tr>
<tr>
<th>Student: </th>
<td><?php echo $survey->getStudentId() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $survey->getUserId() ?></td>
</tr>
<tr>
<th>Survey date: </th>
<td><?php echo $survey->getSurveyDate() ?></td>
</tr>
<tr>
<th>Family condition: </th>
<td><?php echo $survey->getFamilyCondition() ?></td>
</tr>
<tr>
<th>Grade: </th>
<td><?php echo $survey->getGrade() ?></td>
</tr>
<tr>
<th>Other assist: </th>
<td><?php echo $survey->getOtherAssist() ?></td>
</tr>
<tr>
<th>Dropout info: </th>
<td><?php echo $survey->getDropoutInfo() ?></td>
</tr>
<tr>
<th>Presentation: </th>
<td><?php echo $survey->getPresentation() ?></td>
</tr>
<tr>
<th>Revenue: </th>
<td><?php echo $survey->getRevenue() ?></td>
</tr>
<tr>
<th>Property: </th>
<td><?php echo $survey->getProperty() ?></td>
</tr>
<tr>
<th>Donation usage: </th>
<td><?php echo $survey->getDonationUsage() ?></td>
</tr>
<tr>
<th>Donor concerned: </th>
<td><?php echo $survey->getDonorConcerned() ?></td>
</tr>
<tr>
<th>Msg to donor: </th>
<td><?php echo $survey->getMsgToDonor() ?></td>
</tr>
<tr>
<th>Msg to stu: </th>
<td><?php echo $survey->getMsgToStu() ?></td>
</tr>
<tr>
<th>School opinion: </th>
<td><?php echo $survey->getSchoolOpinion() ?></td>
</tr>
<tr>
<th>Teacher opinion: </th>
<td><?php echo $survey->getTeacherOpinion() ?></td>
</tr>
<tr>
<th>User opinion: </th>
<td><?php echo $survey->getUserOpinion() ?></td>
</tr>
<tr>
<th>Discription: </th>
<td><?php echo $survey->getDiscription() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $survey->getCreatedAt() ?></td>
</tr>
</tbody>
</table>
<?php endif;?>








</div>


