<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:33:07
?>
<div id="sf_admin_container">

<h1>到款信息</h1>
<?php echo link_to('修改', 'remit/edit?remit_id='.$remit->getRemitId()) ?>
&nbsp;<?php echo link_to('返回', 'remit/list') ?>
<?php use_helper('Object') ?>

<div id="sf_admin_content">
<table>
  <tbody>
  <tr>
    <td class="name">到款号：</td>
    <td class="content"><?php echo $remit->getRemitId() ?></td>
  </tr>
  <tr>
    <td class="name">捐助号：</td>
    <td class="content"><?php echo $remit->getDonationId() ?></td>
  </tr>

  <tr>
    <td class="name">数额：</td>
    <td class="content"><?php echo $remit->getAmount() ?></td>
  </tr>
  
  <?php if($remit->getIsByOfs()):?>
  <tr>
    <td class="name">通过OFS捐助：</td>
    <td class="content"><?php echo image_tag('admin_db/tick.png');?></td>
  </tr>    

  <tr>
    <td class="name">已收到：</td>
    <td class="content"><?php
              if($remit->getIsReceived())
	 		    echo image_tag('admin_db/tick.png');
	          else
	            echo image_tag('admin_db/x.png');	 
    ?></td>
  </tr>
  
  <tr>
    <td class="name">收款日期：</td>
    <td class="content"><?php echo $remit->getReceiveDate() ?></td>
  </tr>
  
  <tr>
    <td class="name">收款人：</td>
    <td class="content"><?php if ($remit->getReceiveUserId()) echo $remit->getUserRelatedByReceiveUserId()->getName()?></td>
  </tr>
  
  <tr>
    <td class="name">已发送：</td>
    <td class="content"><?php
              if($remit->getIsSendout())
	 		    echo image_tag('admin_db/tick.png');
	          else
	            echo image_tag('admin_db/x.png');	 
    ?></td>
  </tr>
  
  <tr>
    <td class="name">发款日期：</td>
    <td class="content"><?php echo $remit->getSendoutDate() ?></td>
  </tr>
  
  <tr>
    <td class="name">发款人：</td>
    <td class="content"><?php if ($remit->getSendoutUserId()) echo $remit->getUserRelatedBySendoutUserId()->getName()?></td>
  </tr>                                  

  <tr>
    <td class="name">创建日期：</td>
    <td class="content"><?php echo $remit->getCreatedAt() ?></td>
  </tr>    
  <?php else:?>
  <tr>
    <td class="name">通过OFS捐助：</td>
    <td class="content"><?php echo image_tag('admin_db/x.png');?></td>
  </tr>
   
  <tr>
    <td class="name">已发送：</td>
    <td class="content"><?php
              if($remit->getIsSendout())
	 		    echo image_tag('admin_db/tick.png');
	          else
	            echo image_tag('admin_db/x.png');	 
    ?></td>
  </tr>
  
  <tr>
    <td class="name">发款日期：</td>
    <td class="content"><?php echo $remit->getSendoutDate() ?></td>
  </tr>    
  <?php endif;?>
  </tbody>
</table>

</div>

