<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/09/27 10:16:09
sfConfig::add(array(
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => true,
  'library' => 'gd_mime_type',
),
  'app_homepage_max' => 15,
  'app_active_days' => 7,
  'app_pager_max' => 15,
  'app_recent_pager_max' => 45,
));
