<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/09/15 07:54:03
sfConfig::add(array(
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => true,
  'library' => 'gd_mime_type',
),
  'app_homepage_max' => 10,
  'app_active_days' => 7,
  'app_pager_max' => 10,
  'app_tinymce_options' => 'theme:"advanced",
plugins:"safari,pagebreak,style,layer,table,filemanager,imagemanager,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount",
theme_advanced_toolbar_location:"top",
theme_advanced_toolbar_align:"left",
theme_advanced_buttons1:"preview,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,forecolor,backcolor,|,fontselect,fontsizeselect",
theme_advanced_buttons2:"paste,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,image,code,|,insertdate,inserttime",
theme_advanced_buttons3:"tablecontrols,|,hr,removeformat,|,sub,sup,|,charmap,emotions,media,|,fullscreen",
imagemanager_remember_last_path : false,
theme_advanced_resizing:false',
));
