<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/09/15 03:55:15

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://root@localhost/qqchong',
), 'propel');
$this->databases['propel'] = $database;
