<?php
// auto-generated by sfSecurityConfigHandler
// date: 2009/09/15 03:55:15
$this->security = array (
  'create' => 
  array (
    'is_secure' => false,
  ),
  'login' => 
  array (
    'is_secure' => false,
  ),
  'update' => 
  array (
    'is_secure' => false,
  ),
  'passwordrequest' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
