<?php
// auto-generated by sfValidatorConfigHandler
// date: 2009/09/17 04:08:51

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
  'enabled' => true,
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['sfEmailValidator_email'] = new sfEmailValidator();
  $validators['sfEmailValidator_email']->initialize($context, array (
  'email_error' => 'Invalid Email address',
));
  $validatorManager->registerName('email', 1, 'Email is required', null, null, false);
  $validatorManager->registerValidator('email', $validators['sfEmailValidator_email'], null);
  $context->getRequest()->setAttribute('fillin', array (
  'enabled' => true,
), 'symfony/filter');
}
