<?php
// auto-generated by sfValidatorConfigHandler
// date: 2009/09/15 08:29:43

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
  'enabled' => true,
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['sfStringValidator_title'] = new sfStringValidator();
  $validators['sfStringValidator_title']->initialize($context, array (
  'max' => 32,
  'max_error' => 'At most 32 chars',
));
  $validatorManager->registerName('title', 1, 'Please enter title', null, null, false);
  $validatorManager->registerValidator('title', $validators['sfStringValidator_title'], null);
  $validatorManager->registerName('content', 1, 'Please enter content', null, null, false);
  $context->getRequest()->setAttribute('fillin', array (
  'enabled' => true,
), 'symfony/filter');
}
