<?php
// auto-generated by sfPropelCrud
// date: 2009/07/19 21:33:07
?>
<div id="sf_admin_container">

<h1>到款信息详情</h1>

<?php use_helper('Object') ?>

<div id="sf_admin_content">
<table>
  <tbody>
  <tr>
    <td class="name">到款号：</td>
    <td class="content"><?php echo $remit->getRemitId() ?></td>
  </tr>
  <tr>
    <td class="name">捐助人：</td>
    <td class="content"><?php echo $remit->getDonation()->getUser()->getName() ?></td>
  </tr>  
  <tr>
    <td class="name">捐助号：</td>
    <td class="content"><?php echo $remit->getDonationId() ?></td>
  </tr>

  <tr>
    <td class="name">数额：</td>
    <td class="content"><?php echo $remit->getAmount() ?></td>
  </tr>
  
  <?php if($remit->getIsByOfs()):?>
  <tr>
    <td class="name">通过OFS捐助：</td>
    <td class="content"><?php echo image_tag('admin_db/tick.png');?></td>
  </tr>    

  <tr>
    <td class="name">OFS收到：</td>
    <td class="content"><?php
              if($remit->getIsReceived())
	 		    echo image_tag('admin_db/tick.png');
	          else
	            echo image_tag('admin_db/x.png');	 
    ?></td>
  </tr>
  
  <tr>
    <td class="name">收款日期：</td>
    <td class="content"><?php echo $remit->getReceiveDate() ?></td>
  </tr>
  
  <tr>
    <td class="name">收款人：</td>
    <td class="content"><?php if ($remit->getReceiveUserId()) echo $remit->getUserRelatedByReceiveUserId()->getName()?></td>
  </tr>

  <tr>
    <td class="name">收款金额：</td>
    <td class="content"><?php echo $remit->getReceiveAmount() ?></td>
  </tr>
  
  <tr>
    <td class="name">收款录入人：</td>
    <td class="content"><?php if ($remit->getReceiveSubmitter()) echo $remit->getUserRelatedByReceiveSubmitter()->getName()?></td>
  </tr>
    
  <tr>
    <td class="name">OFS发送：</td>
    <td class="content"><?php
              if($remit->getIsSendout())
	 		    echo image_tag('admin_db/tick.png');
	          else
	            echo image_tag('admin_db/x.png');	 
    ?></td>
  </tr>
  
  <tr>
    <td class="name">发款日期：</td>
    <td class="content"><?php echo $remit->getSendoutDate() ?></td>
  </tr>
  
  <tr>
    <td class="name">发款人：</td>
    <td class="content"><?php if ($remit->getSendoutUserId()) echo $remit->getUserRelatedBySendoutUserId()->getName()?></td>
  </tr>                                  

  <tr>
    <td class="name">发款金额：</td>
    <td class="content"><?php echo $remit->getSendoutAmount() ?></td>
  </tr>  
  
  <tr>
    <td class="name">创建日期：</td>
    <td class="content"><?php echo $remit->getCreatedAt() ?></td>
  </tr>
  
  <tr>
    <td class="name">发款录入人：</td>
    <td class="content"><?php if ($remit->getSendoutSubmitter()) echo $remit->getUserRelatedBySendoutSubmitter()->getName()?></td>
  </tr>
  
  <tr>
    <td class="name">创建时间：</td>
    <td class="content"><?php echo $remit->getCreatedAt() ?></td>
  </tr>
  
  <tr>
    <td class="name">走访报告：</td>
    <td class="content">
    <?php 
      if($remit->getReportId()) 
         echo link_to('点击访问','reportcard/show?report_id='.$remit->getReportId());
      else
         echo "无";
    ?></td>
  </tr>
  
  <tr>
    <td class="name">发放详情：</td>
    <td class="content"><?php echo $remit->getDiscription() ?></td>
  </tr>
  
  <tr>
    <td class="name">备注：</td>
    <td class="content"><?php echo $remit->getRemark() ?></td>
  </tr>                                       
        
  <?php else:?>
  <tr>
    <td class="name">通过OFS捐助：</td>
    <td class="content"><?php echo image_tag('admin_db/x.png');?></td>
  </tr>
   
  <tr>
    <td class="name">已发送：</td>
    <td class="content"><?php
              if($remit->getIsSendout())
	 		    echo image_tag('admin_db/tick.png');
	          else
	            echo image_tag('admin_db/x.png');	 
    ?></td>
  </tr>
  
  <tr>
    <td class="name">发款日期：</td>
    <td class="content"><?php echo $remit->getSendoutDate() ?></td>
  </tr>
      
  <?php endif;?>
  </tbody>
</table>

<?php //echo link_to('修改', 'remit/edit?remit_id='.$remit->getRemitId()) ?>
<?php if ($sf_params->has('after_edit')): ?>
<a href="javascript:history.go(-2)">返回</a>
<?php else:?>
<a href="javascript:history.go(-1)">返回</a>
<?php endif;?>   
</div>

