<?php
// auto-generated by sfSecurityConfigHandler
// date: 2009/07/24 18:04:08
$this->security = array (
  'create' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'manager',
        1 => 'administrator',
      ),
    ),
  ),
  'edit' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'manager',
        1 => 'administrator',
      ),
    ),
  ),
  'delete' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'manager',
        1 => 'administrator',
      ),
    ),
  ),
  'listall' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'surveyor',
        1 => 'manager',
        2 => 'administrator',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
